'use client';

import { useCallback, useEffect, useMemo, useState, type CSSProperties, type ReactNode } from 'react';
import { Activity, AlertTriangle, BarChart3, CalendarDays, Clock, Flag, Gauge, LayoutGrid, Loader2, MapPin, RefreshCw, Shield, Sparkles, Target, Trophy, UserRound, Users, Zap } from 'lucide-react';
import { getTeamFlagUrl } from '@/lib/teamFlags';

type Props = { matchId?: string | number | null; dbMatchId?: string | number | null };
type Team = { id: string; name: string; code?: string | null; image?: string | null };
type MatchInfo = { id: string; status?: string | null; matchDate?: string | null; homeScore?: number | null; awayScore?: number | null; homeTeam: Team; awayTeam: Team; groupPhase?: string | null; stage?: string | null; venue?: string | null; referee?: string | null; city?: string | null; kickoff?: string | null; attendance?: string | number | null; weather?: string | null };
type UnknownRecord = Record<string, unknown>;
type Snapshot = UnknownRecord;
type PlayerAsset = { name?: string | null; image?: string | null; position?: string | null };
type MatchEvent = { id: string; minute?: number | null; minuteLabel?: string | null; type?: string | null; detail?: string | null; teamId?: string | null; playerName?: string | null; playerImage?: string | null; playerAsset?: PlayerAsset | null; x?: number | null; y?: number | null };
type StatsResponse = { ok?: boolean; match?: MatchInfo | null; latest?: Snapshot | null; history?: Snapshot[] | null };
type EventsResponse = { ok?: boolean; events?: MatchEvent[] | null };
type StatDef = { key: string; label: string; icon: ReactNode; homeKeys: string[]; awayKeys: string[]; aliases: string[]; suffix?: string };
type StatRow = StatDef & { home: number | null; away: number | null; max: number };
type Side = 'home' | 'away' | 'neutral';
type TabId = 'overview' | 'stats' | 'pitch' | 'events' | 'momentum' | 'history' | 'group';
type H2HRow = { date: string; score: string; competition: string; homeScore?: number | null; awayScore?: number | null };
type LastMatchRow = { result: 'W' | 'D' | 'L' | '-'; opponent: string; score: string; date?: string };
type StandingRow = { rank: number; team: Team; played: number; won: number; drawn: number; lost: number; gd: number; pts: number };

const HOME = '#3b82f6', AWAY = '#ef4444', GOLD = '#facc15';
const ar = new Intl.NumberFormat('ar-EG');
const phases = [[0, 15], [15, 30], [30, 45], [45, 60], [60, 75], [75, 90]] as const;
const statDefs: StatDef[] = [
  { key: 'possession', label: 'الاستحواذ', icon: <Gauge size={15} />, homeKeys: ['homePossession'], awayKeys: ['awayPossession'], aliases: ['possession', 'ballPossession', 'ball_possession'], suffix: '%' },
  { key: 'shots', label: 'التسديدات', icon: <Target size={15} />, homeKeys: ['homeShots'], awayKeys: ['awayShots'], aliases: ['shots', 'totalShots', 'total_shots'] },
  { key: 'shotsOnTarget', label: 'على المرمى', icon: <Zap size={15} />, homeKeys: ['homeShotsOnTarget'], awayKeys: ['awayShotsOnTarget'], aliases: ['shotsOnTarget', 'shots_on_target', 'shotsOnGoal'] },
  { key: 'dangerousAttacks', label: 'هجمات خطيرة', icon: <Activity size={15} />, homeKeys: ['homeDangerousAttacks'], awayKeys: ['awayDangerousAttacks'], aliases: ['dangerousAttacks', 'dangerous_attacks'] },
  { key: 'attacks', label: 'الهجمات', icon: <BarChart3 size={15} />, homeKeys: ['homeAttacks'], awayKeys: ['awayAttacks'], aliases: ['attacks', 'total_attacks'] },
  { key: 'corners', label: 'الركنيات', icon: <Flag size={15} />, homeKeys: ['homeCorners'], awayKeys: ['awayCorners'], aliases: ['corners', 'cornerKicks', 'corner_kicks'] },
  { key: 'yellowCards', label: 'بطاقات صفراء', icon: <Shield size={15} />, homeKeys: ['homeYellowCards'], awayKeys: ['awayYellowCards'], aliases: ['yellowCards', 'yellow_cards'] },
  { key: 'redCards', label: 'بطاقات حمراء', icon: <Shield size={15} />, homeKeys: ['homeRedCards'], awayKeys: ['awayRedCards'], aliases: ['redCards', 'red_cards'] },
  { key: 'shotsOffTarget', label: 'خارج المرمى', icon: <Target size={15} />, homeKeys: ['homeShotsOffTarget'], awayKeys: ['awayShotsOffTarget'], aliases: ['shotsOffTarget', 'shots_off_target', 'shotsOffGoal'] },
];
const statPriority = statDefs.map((s) => s.key);
const tabs: Array<{ id: TabId; label: string; icon: ReactNode }> = [
  { id: 'overview', label: 'نظرة عامة', icon: <LayoutGrid size={15} /> },
  { id: 'stats', label: 'الإحصائيات', icon: <BarChart3 size={15} /> },
  { id: 'pitch', label: 'الملعب', icon: <Target size={15} /> },
  { id: 'events', label: 'الأحداث', icon: <Clock size={15} /> },
  { id: 'momentum', label: 'الزخم والقصة', icon: <Zap size={15} /> },
  { id: 'history', label: 'السجل', icon: <Trophy size={15} /> },
  { id: 'group', label: 'المجموعة', icon: <Users size={15} /> },
];

function asRecord(value: unknown): UnknownRecord | null { return value && typeof value === 'object' && !Array.isArray(value) ? (value as UnknownRecord) : null; }
function asList(value: unknown): unknown[] { if (Array.isArray(value)) return value; const r = asRecord(value); if (!r) return []; for (const k of ['all', 'rows', 'items', 'data', 'results', 'matches', 'meetings', 'standings', 'table', 'last5', 'lastFive']) { const v = r[k]; if (Array.isArray(v)) return v; } return []; }
function toNumber(value: unknown): number | null { if (value === null || value === undefined || value === '') return null; const n = Number(typeof value === 'string' ? value.replace('%', '').trim() : value); return Number.isFinite(n) ? n : null; }
function text(value: unknown): string { return String(value ?? '').trim(); }
function fmt(value: number | string | null | undefined, suffix = '') { if (value === null || value === undefined || value === '') return '—'; const n = Number(value); return Number.isFinite(n) ? `${Number.isInteger(n) ? ar.format(n) : n.toLocaleString('ar-EG', { maximumFractionDigits: 2 })}${suffix}` : String(value); }
function dateAr(value?: string | null) { if (!value) return 'غير متوفر'; const d = new Date(value); return Number.isFinite(d.getTime()) ? new Intl.DateTimeFormat('ar-EG', { dateStyle: 'medium', timeStyle: 'short' }).format(d) : 'غير متوفر'; }
function norm(value?: string | null) { return String(value || '').trim().toLowerCase().replace(/\s+/g, ' '); }
function teamName(team?: Team | null) { return team?.name || team?.code || 'منتخب غير معروف'; }
function flagUrl(team?: Team | null) { return team ? getTeamFlagUrl({ code: team.code, name: team.name, image: team.image }, 160) || team.image || null : null; }
function statusKind(status?: string | null) { const s = norm(status).toUpperCase(); if (['LIVE', 'IN_PLAY', '1H', '2H', 'HT', 'HALFTIME'].includes(s)) return 'live'; if (['FINISHED', 'FT', 'AET', 'PEN', 'COMPLETED', 'ENDED'].includes(s)) return 'finished'; return 'scheduled'; }
function eventIcon(type?: string | null, detail?: string | null) { const v = norm(`${type || ''} ${detail || ''}`); if (v.includes('goal') || v.includes('هدف')) return '⚽'; if (v.includes('shot') || v.includes('تسديد')) return '🎯'; if (v.includes('yellow') || v.includes('صفراء')) return '🟨'; if (v.includes('red') || v.includes('حمراء') || v.includes('طرد')) return '🟥'; if (v.includes('corner') || v.includes('ركنية')) return '🚩'; if (v.includes('sub')) return '🔁'; return '●'; }
function eventWeight(e: MatchEvent) { const icon = eventIcon(e.type, e.detail); if (icon === '⚽') return 5; if (icon === '🎯') return 3; if (icon === '🚩') return 2; if (icon === '🟥') return 2; return 1; }
function eventColor(e: MatchEvent) { const icon = eventIcon(e.type, e.detail); if (icon === '⚽') return GOLD; if (icon === '🎯') return '#60a5fa'; if (icon === '🟨') return '#facc15'; if (icon === '🟥') return '#ef4444'; if (icon === '🚩') return '#22d3ee'; return '#e5e7eb'; }
function sideOfEvent(e: MatchEvent, match: MatchInfo | null): Side { if (!match) return 'neutral'; if (e.teamId && e.teamId === match.homeTeam.id) return 'home'; if (e.teamId && e.teamId === match.awayTeam.id) return 'away'; const blob = norm(`${e.detail || ''} ${e.playerName || ''}`); if (blob.includes(norm(match.homeTeam.name))) return 'home'; if (blob.includes(norm(match.awayTeam.name))) return 'away'; return 'neutral'; }
function getRecordPath(root: UnknownRecord | null, path: string[]): unknown { let current: unknown = root; for (const key of path) current = asRecord(current)?.[key]; return current; }
function recordsFromSnapshot(snapshot: Snapshot | null | undefined): UnknownRecord[] { const base = asRecord(snapshot); if (!base) return []; const raw = asRecord(base.rawData); return [base, raw, getRecordPath(raw, ['stats']), getRecordPath(raw, ['providerStats']), getRecordPath(raw, ['overview']), getRecordPath(raw, ['theStatsApi', 'stats']), getRecordPath(raw, ['theStatsApi', 'providerStats']), getRecordPath(raw, ['liveStats', 'stats']), getRecordPath(raw, ['liveStats', 'providerStats']), getRecordPath(raw, ['normalized', 'liveStats', 'stats'])].map(asRecord).filter((r): r is UnknownRecord => Boolean(r)); }
function pairFromObject(value: unknown): { home: number | null; away: number | null } | null { const r = asRecord(value); if (!r) return null; const all = asRecord(r.all); const home = toNumber(r.home ?? r.homeValue ?? r.home_value ?? all?.home); const away = toNumber(r.away ?? r.awayValue ?? r.away_value ?? all?.away); return home === null && away === null ? null : { home, away }; }
function readStat(def: StatDef, snapshots: Snapshot[]): StatRow { for (const snap of snapshots) { const records = recordsFromSnapshot(snap); for (const r of records) { for (const alias of def.aliases) { const pair = pairFromObject(r[alias]); if (pair) return { ...def, ...pair, max: Math.max(pair.home ?? 0, pair.away ?? 0, 1) }; } const home = def.homeKeys.map((k) => toNumber(r[k])).find((v) => v !== null) ?? null; const away = def.awayKeys.map((k) => toNumber(r[k])).find((v) => v !== null) ?? null; if (home !== null || away !== null) return { ...def, home, away, max: Math.max(home ?? 0, away ?? 0, 1) }; } } return { ...def, home: null, away: null, max: 1 }; }
function eventMinute(e: MatchEvent) { const n = toNumber(e.minute); if (n !== null) return n; const m = text(e.minuteLabel).match(/\d+/); return m ? Number(m[0]) : 0; }
function eventPoint(e: MatchEvent, i: number, match: MatchInfo | null) { const side = sideOfEvent(e, match); const rawX = toNumber(e.x); const rawY = toNumber(e.y); const base = side === 'away' ? 70 : side === 'home' ? 30 : 50; const x0 = rawX !== null ? rawX : base + ((i * 13) % 18) - 9; const y0 = rawY !== null ? rawY : 18 + ((i * 23 + eventMinute(e) * 3) % 64); const x = side === 'home' ? Math.min(48, Math.max(4, x0)) : side === 'away' ? Math.max(52, Math.min(96, x0)) : Math.min(96, Math.max(4, x0)); return { x, y: Math.min(92, Math.max(8, y0)), side }; }
function snapshotRoots(snapshots: Snapshot[]) { return snapshots.flatMap((snap) => { const base = asRecord(snap); const raw = asRecord(base?.rawData); return [base, raw, asRecord(raw?.normalized), asRecord(raw?.data), asRecord(raw?.theStatsApi), asRecord(raw?.liveStats)].filter((r): r is UnknownRecord => Boolean(r)); }); }
function findFirstArray(snapshots: Snapshot[], keys: string[][]) { const roots = snapshotRoots(snapshots); for (const root of roots) for (const path of keys) { const arr = asList(getRecordPath(root, path)); if (arr.length) return arr; } return []; }
function rowText(row: UnknownRecord, keys: string[], fallback = '—') { for (const key of keys) { const value = row[key]; if (typeof value === 'string' || typeof value === 'number') { const t = text(value); if (t) return t; } const nested = asRecord(value); if (nested) { const t = text(nested.name ?? nested.title ?? nested.label); if (t) return t; } } return fallback; }
function teamFromRow(row: UnknownRecord): Team { const team = asRecord(row.team) || asRecord(row.asset) || row; return { id: text(asRecord(team)?.id ?? row.id ?? row.teamId ?? row.team_id ?? row.code ?? row.name), name: rowText(asRecord(team) || row, ['name', 'teamName', 'team_name', 'title', 'label'], 'منتخب'), code: text(asRecord(team)?.code ?? row.code) || null, image: text(asRecord(team)?.image ?? row.image ?? row.logo ?? row.flag) || null }; }
function h2hRows(snapshots: Snapshot[]): H2HRow[] { return findFirstArray(snapshots, [['h2h'], ['headToHead'], ['head_to_head'], ['meetings'], ['h2h', 'meetings'], ['headToHead', 'matches']]).slice(0, 5).map((item) => { const r = asRecord(item) || {}; const hs = toNumber(r.homeScore ?? r.home_score); const as = toNumber(r.awayScore ?? r.away_score); return { date: rowText(r, ['date', 'matchDate', 'kickoff'], '—'), score: rowText(r, ['score', 'scoreLine'], hs !== null || as !== null ? `${fmt(hs)} - ${fmt(as)}` : '—'), competition: rowText(r, ['competition', 'league', 'stage', 'tournament'], '—'), homeScore: hs, awayScore: as }; }); }
function lastRows(snapshots: Snapshot[], side: 'home' | 'away'): LastMatchRow[] { const arr = findFirstArray(snapshots, [[`lastMatches`, side], ['lastMatches', `${side}Team`], ['form', side], ['recentMatches', side], [`${side}LastMatches`], [`${side}_last_matches`]]); return arr.slice(0, 5).map((item) => { const r = asRecord(item) || {}; const res = rowText(r, ['result', 'outcome'], '-').toUpperCase(); return { result: res === 'W' || res === 'D' || res === 'L' ? res : '-', opponent: rowText(r, ['opponent', 'opponentName', 'against', 'teamName'], '—'), score: rowText(r, ['score', 'scoreLine'], '—'), date: rowText(r, ['date', 'matchDate'], '') }; }); }
function standingRows(snapshots: Snapshot[]): StandingRow[] { return findFirstArray(snapshots, [['standings'], ['groupStandings'], ['table'], ['group', 'standings'], ['group', 'table'], ['normalized', 'standings']]).slice(0, 12).map((item, index) => { const r = asRecord(item) || {}; return { rank: toNumber(r.rank ?? r.position) ?? index + 1, team: teamFromRow(r), played: toNumber(r.played ?? r.p) ?? 0, won: toNumber(r.won ?? r.w) ?? 0, drawn: toNumber(r.drawn ?? r.d) ?? 0, lost: toNumber(r.lost ?? r.l) ?? 0, gd: toNumber(r.goalDifference ?? r.gd ?? r.diff) ?? 0, pts: toNumber(r.points ?? r.pts) ?? 0 }; }); }

function Card({ children, className = '', style }: { children: ReactNode; className?: string; style?: CSSProperties }) { return <section style={style} className={`rounded-3xl border border-white/[0.08] bg-white/[0.03] shadow-2xl shadow-black/20 ${className}`}>{children}</section>; }
function Title({ title, icon, small = false }: { title: string; icon: ReactNode; small?: boolean }) { return <h2 className={`mb-4 flex items-center gap-2 font-black text-white ${small ? 'text-base' : 'text-xl'}`}>{icon}<span>{title}</span></h2>; }
function EmptyLine({ text: value }: { text: string }) { return <div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm font-bold text-slate-500">{value}</div>; }
function Spinner() { return <div className="flex min-h-[65vh] items-center justify-center bg-slate-950 text-white" dir="rtl"><Loader2 className="ml-3 animate-spin text-blue-400" /> جارٍ تحميل مركز المباراة...</div>; }
function MiniFlag({ team }: { team: Team }) { const src = flagUrl(team); return <span className="inline-flex h-6 w-8 items-center justify-center overflow-hidden rounded-lg bg-black/30">{src ? <img src={src} alt={teamName(team)} className="h-full w-full object-cover" /> : team.code}</span>; }
function ScoreBox({ label, value, color }: { label: string; value: string | number; color: string }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-4 text-center"><b className={`block text-2xl font-black ${color}`}>{value}</b><span className="mt-1 block text-xs font-bold text-slate-500">{label}</span></div>; }
function Tabs({ active, setActive, counts }: { active: TabId; setActive: (tab: TabId) => void; counts: Partial<Record<TabId, number>> }) { return <Card className="sticky top-2 z-40 p-2 backdrop-blur-xl"><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <button key={tab.id} onClick={() => setActive(tab.id)} className={`inline-flex h-11 shrink-0 items-center gap-2 rounded-2xl border px-4 text-xs font-black transition ${active === tab.id ? 'border-blue-400/50 bg-blue-500 text-white shadow-lg shadow-blue-500/20' : 'border-white/10 bg-white/[0.04] text-slate-300 hover:bg-white/[0.08]'}`}>{tab.icon}<span>{tab.label}</span>{counts[tab.id] ? <b className="rounded-full bg-black/20 px-2 py-0.5 text-[10px]">{ar.format(counts[tab.id] || 0)}</b> : null}</button>)}</div></Card>; }

function TeamFlag({ team, accent }: { team?: Team | null; accent: string }) { const src = flagUrl(team); return <div className="mx-auto flex h-20 w-20 items-center justify-center overflow-hidden rounded-full border-2 bg-slate-900 shadow-xl sm:h-24 sm:w-24" style={{ borderColor: accent }}>{src ? <img src={src} alt={teamName(team)} className="h-full w-full object-cover" /> : <span className="text-xl font-black">{team?.code || '—'}</span>}</div>; }
function Meta({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-3"><div className="mb-1 flex items-center gap-2 text-slate-500">{icon}<span>{label}</span></div><b className="block truncate text-white">{value}</b></div>; }
function Hero({ match }: { match: MatchInfo }) { const kind = statusKind(match.status); return <Card className="relative overflow-hidden p-5 sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(59,130,246,.25),transparent_35%),radial-gradient(circle_at_bottom,rgba(239,68,68,.22),transparent_35%)]" /><div className="absolute inset-0 opacity-15 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:38px_38px]" /><div className="relative z-10"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><span className="rounded-full border border-white/10 bg-black/25 px-4 py-2 text-xs font-black text-slate-200">{match.stage || match.groupPhase || 'كأس العالم 2026'}</span><span className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-xs font-black ${kind === 'live' ? 'border-red-400/40 bg-red-500/10 text-red-200' : 'border-white/10 bg-white/5 text-slate-200'}`}>{kind === 'live' ? <i className="h-2.5 w-2.5 animate-pulse rounded-full bg-red-500" /> : null}{kind === 'live' ? 'مباشر الآن' : kind === 'finished' ? 'انتهت المباراة' : 'لم تبدأ بعد'}</span></div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="min-w-0 text-center"><TeamFlag team={match.homeTeam} accent={HOME} /><h1 className="mt-3 truncate text-lg font-black sm:text-3xl">{teamName(match.homeTeam)}</h1></div><div className="rounded-[2rem] border border-white/10 bg-black/35 px-4 py-4 text-center sm:px-8"><div className="flex items-center justify-center gap-3 text-5xl font-black tabular-nums sm:text-7xl"><span className="animate-pulse text-blue-400">{fmt(match.homeScore)}</span><span className="text-white/50">-</span><span className="animate-pulse text-red-400">{fmt(match.awayScore)}</span></div><p className="mt-2 text-xs font-bold text-slate-400">{dateAr(match.kickoff || match.matchDate)}</p></div><div className="min-w-0 text-center"><TeamFlag team={match.awayTeam} accent={AWAY} /><h1 className="mt-3 truncate text-lg font-black sm:text-3xl">{teamName(match.awayTeam)}</h1></div></div><div className="mt-6 grid gap-2 text-xs font-bold text-slate-300 sm:grid-cols-2 lg:grid-cols-5"><Meta icon={<MapPin size={15} />} label="الملعب" value={match.venue || 'غير متوفر'} /><Meta icon={<UserRound size={15} />} label="الحكم" value={match.referee || 'غير متوفر'} /><Meta icon={<MapPin size={15} />} label="المدينة" value={match.city || 'غير متوفر'} /><Meta icon={<CalendarDays size={15} />} label="الموعد" value={dateAr(match.matchDate)} /><Meta icon={<Users size={15} />} label="الحضور" value={fmt(match.attendance)} /></div></div></Card>; }

function StatsPanel({ stats }: { stats: StatRow[] }) { return <Card className="p-4 sm:p-5"><Title icon={<BarChart3 />} title="إحصائيات المباراة" /><div className="space-y-3">{stats.map((s) => { const hp = s.home === null ? 0 : Math.round((s.home / s.max) * 100); const ap = s.away === null ? 0 : Math.round((s.away / s.max) * 100); return <div key={s.key} className="grid grid-cols-[48px_1fr_120px_1fr_48px] items-center gap-2 rounded-2xl border border-white/[0.06] bg-black/20 p-3 text-xs sm:grid-cols-[70px_1fr_160px_1fr_70px]"><b className="text-center text-blue-300">{fmt(s.home, s.suffix)}</b><div className="h-2 overflow-hidden rounded-full bg-white/10" dir="ltr"><div className="h-full rounded-full bg-blue-500 transition-all duration-1000" style={{ width: `${hp}%` }} /></div><div className="flex items-center justify-center gap-2 text-center font-black text-white">{s.icon}<span>{s.label}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-red-500 transition-all duration-1000" style={{ width: `${ap}%` }} /></div><b className="text-center text-red-300">{fmt(s.away, s.suffix)}</b></div>; })}</div></Card>; }
function PitchMap({ events, match }: { events: MatchEvent[]; match: MatchInfo | null }) { const points = useMemo(() => events.map((e, i) => ({ e, ...eventPoint(e, i, match) })), [events, match]); const zones = useMemo(() => Array.from({ length: 6 }, (_, z) => points.filter((p) => Math.floor(p.x / 33.34) + Math.floor(p.y / 50) * 3 === z).length), [points]); const maxZone = Math.max(...zones, 1); return <Card className="p-4 sm:p-5"><Title icon={<Target />} title="خريطة الملعب التفاعلية" /><svg viewBox="0 0 100 64" className="h-auto w-full rounded-3xl border border-white/10 bg-emerald-950"><rect width="100" height="64" fill="#064e3b" />{zones.map((count, z) => <rect key={z} x={(z % 3) * 33.333} y={Math.floor(z / 3) * 32} width="33.333" height="32" fill={count ? '#facc15' : 'transparent'} opacity={count ? 0.08 + (count / maxZone) * 0.28 : 0} />)}<rect x="3" y="3" width="94" height="58" fill="none" stroke="white" strokeOpacity=".72" strokeWidth=".7" /><line x1="50" y1="3" x2="50" y2="61" stroke="white" strokeOpacity=".55" strokeWidth=".55" /><circle cx="50" cy="32" r="8" fill="none" stroke="white" strokeOpacity=".55" strokeWidth=".55" /><rect x="3" y="18" width="14" height="28" fill="none" stroke="white" strokeOpacity=".55" strokeWidth=".55" /><rect x="83" y="18" width="14" height="28" fill="none" stroke="white" strokeOpacity=".55" strokeWidth=".55" /><rect x="3" y="24" width="5" height="16" fill="none" stroke="white" strokeOpacity=".55" strokeWidth=".55" /><rect x="92" y="24" width="5" height="16" fill="none" stroke="white" strokeOpacity=".55" strokeWidth=".55" />{points.map(({ e, x, y }, i) => { const icon = eventIcon(e.type, e.detail); const fill = eventColor(e); return <g key={`${e.id}-${i}`} className="cursor-pointer"><title>{`${e.minuteLabel || e.minute || '—'} · ${icon} · ${e.playerName || e.playerAsset?.name || 'لاعب'} · ${e.detail || e.type || 'حدث'}`}</title>{icon === '⚽' ? <text x={x} y={y + 1.4} textAnchor="middle" fontSize="4.7" fill={GOLD}>★</text> : <circle cx={x} cy={y} r="1.7" fill={fill} stroke="white" strokeOpacity=".85" strokeWidth=".35" />}</g>; })}</svg><div className="mt-3 flex flex-wrap justify-center gap-2 text-xs font-bold text-slate-300">{['⚽ هدف', '🎯 تسديدة', '🟨 بطاقة صفراء', '🟥 بطاقة حمراء', '🚩 ركنية'].map((x) => <span key={x} className="rounded-full border border-white/10 bg-black/25 px-3 py-1">{x}</span>)}</div></Card>; }
function EventCard({ e, goal, align }: { e: MatchEvent; goal: boolean; align: 'left' | 'right' }) { return <div className={`rounded-2xl border p-3 text-xs transition hover:scale-[1.01] ${goal ? 'border-yellow-300/30 bg-yellow-400/10 shadow-[0_0_30px_rgba(250,204,21,.12)]' : 'border-white/[0.08] bg-black/25'} ${align === 'left' ? 'text-left' : 'text-right'}`}><b className="text-yellow-200">{e.minuteLabel || (e.minute ? `${e.minute}'` : '—')}</b><p className="mt-1 font-black text-white">{e.playerName || e.playerAsset?.name || 'حدث'}</p><p className="mt-1 leading-5 text-slate-400">{e.detail || e.type || '—'}</p></div>; }
function EventsTimeline({ events, match }: { events: MatchEvent[]; match: MatchInfo | null }) { return <Card className="p-4 sm:p-5"><Title icon={<Clock />} title="خط أحداث المباراة" /><div className="relative max-h-[560px] overflow-y-auto pr-1"><div className="absolute left-1/2 top-0 h-full w-px -translate-x-1/2 bg-white/10" /><div className="space-y-3">{events.map((e, i) => { const side = sideOfEvent(e, match); const left = side === 'home'; const goal = eventIcon(e.type, e.detail) === '⚽'; return <div key={`${e.id}-${i}`} className="grid grid-cols-[1fr_34px_1fr] items-center gap-2"><div className={left ? '' : 'opacity-0'}>{left ? <EventCard e={e} goal={goal} align="left" /> : null}</div><div className="z-10 flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-slate-950 text-sm">{eventIcon(e.type, e.detail)}</div><div className={!left ? '' : 'opacity-0'}>{!left ? <EventCard e={e} goal={goal} align="right" /> : null}</div></div>; })}{!events.length ? <EmptyLine text="لم تصل أحداث بعد من API الأحداث" /> : null}</div></div></Card>; }
function H2H({ rows, match }: { rows: H2HRow[]; match: MatchInfo | null }) { const homeWins = rows.filter((r) => (r.homeScore ?? -1) > (r.awayScore ?? 999)).length; const awayWins = rows.filter((r) => (r.awayScore ?? -1) > (r.homeScore ?? 999)).length; const draws = rows.filter((r) => r.homeScore !== null && r.homeScore !== undefined && r.homeScore === r.awayScore).length; return <Card className="p-4 sm:p-5"><Title icon={<Trophy />} title="المواجهات المباشرة" /><div className="mb-4 grid grid-cols-3 gap-2 text-center"><ScoreBox label={`فوز ${teamName(match?.homeTeam)}`} value={homeWins} color="text-blue-300" /><ScoreBox label="تعادل" value={draws} color="text-slate-200" /><ScoreBox label={`فوز ${teamName(match?.awayTeam)}`} value={awayWins} color="text-red-300" /></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-right text-xs"><thead className="text-slate-500"><tr><th className="p-2">التاريخ</th><th className="p-2">النتيجة</th><th className="p-2">البطولة</th></tr></thead><tbody className="divide-y divide-white/10">{rows.map((m, i) => <tr key={`${m.date}-${i}`}><td className="p-2">{m.date}</td><td className="p-2 font-black text-white">{m.score}</td><td className="p-2">{m.competition}</td></tr>)}</tbody></table></div> : <EmptyLine text="المواجهات المباشرة غير متوفرة في بيانات الـ API الحالية" />}</Card>; }
function LastMatches({ home, away, match }: { home: LastMatchRow[]; away: LastMatchRow[]; match: MatchInfo | null }) { return <div className="grid gap-4 lg:grid-cols-2">{[{ team: match?.homeTeam, rows: home }, { team: match?.awayTeam, rows: away }].map((block, idx) => <Card key={block.team?.id || idx} className="p-4"><Title icon={<Activity />} title={`آخر مباريات ${teamName(block.team)}`} small />{block.rows.length ? <div className="space-y-2">{block.rows.map((m, i) => <div key={`${m.opponent}-${i}`} className="flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 p-3 text-xs"><span className={`flex h-7 w-7 items-center justify-center rounded-full font-black ${m.result === 'W' ? 'bg-emerald-500/20 text-emerald-300' : m.result === 'D' ? 'bg-yellow-500/20 text-yellow-200' : m.result === 'L' ? 'bg-red-500/20 text-red-300' : 'bg-slate-500/20 text-slate-300'}`}>{m.result}</span><b>{m.score}</b><span className="text-slate-400">{m.opponent}</span></div>)}</div> : <EmptyLine text="آخر المباريات غير متوفرة في بيانات الـ API الحالية" />}</Card>)}</div>; }
function Standings({ rows, match }: { rows: StandingRow[]; match: MatchInfo | null }) { return <Card className="p-4 sm:p-5"><Title icon={<Users />} title="ترتيب المجموعة" />{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead className="text-slate-500"><tr><th className="p-2">#</th><th className="p-2">المنتخب</th><th className="p-2">P</th><th className="p-2">W</th><th className="p-2">D</th><th className="p-2">L</th><th className="p-2">GD</th><th className="p-2">Pts</th></tr></thead><tbody className="divide-y divide-white/10">{rows.map((r) => { const current = r.team.id === match?.homeTeam.id || r.team.id === match?.awayTeam.id || norm(r.team.name) === norm(match?.homeTeam.name) || norm(r.team.name) === norm(match?.awayTeam.name); return <tr key={`${r.rank}-${r.team.id}`} className={current ? 'bg-white/[0.06]' : ''}><td className="p-2 font-black">{r.rank}</td><td className="flex items-center gap-2 p-2 font-black text-white"><MiniFlag team={r.team} />{teamName(r.team)}</td><td className="p-2">{r.played}</td><td className="p-2">{r.won}</td><td className="p-2">{r.drawn}</td><td className="p-2">{r.lost}</td><td className="p-2">{r.gd > 0 ? `+${r.gd}` : r.gd}</td><td className="p-2 text-yellow-200">{r.pts}</td></tr>; })}</tbody></table></div> : <EmptyLine text="ترتيب المجموعة غير متوفر في بيانات الـ API الحالية" />}</Card>; }
function insightPair(stat: StatRow | undefined, match: MatchInfo | null, fallback: string) { if (!stat || stat.home === null || stat.away === null) return fallback; const home = stat.home, away = stat.away, leader = home === away ? 'تعادل واضح' : home > away ? teamName(match?.homeTeam) : teamName(match?.awayTeam), diff = Math.abs(home - away); return home === away ? `${leader} في ${stat.label}، ولا يوجد طرف مسيطر بوضوح.` : `${leader} يتفوق في ${stat.label} بفارق ${fmt(diff, stat.suffix)}، وهذا يمنحه أفضلية في إيقاع اللعب.`; }
function Intelligence({ stats, match }: { stats: StatRow[]; match: MatchInfo | null }) { const get = (key: string) => stats.find((s) => s.key === key); const poss = get('possession'), da = get('dangerousAttacks'), sot = get('shotsOnTarget'); const insights = [{ title: 'السيطرة على الكرة', accent: HOME, body: insightPair(poss, match, 'الاستحواذ متوازن نسبيًا، والفارق الحقيقي يظهر في جودة الوصول للمناطق الخطيرة.') }, { title: 'تهديد الهجمات الخطيرة', accent: '#f59e0b', body: insightPair(da, match, 'معدل التهديد ما زال مفتوحًا، وأي زيادة في الهجمات الخطيرة قد تغير شكل المباراة.') }, { title: 'جودة التسديد والإنهاء', accent: AWAY, body: `xG تقديري: ${teamName(match?.homeTeam)} ${fmt((sot?.home ?? 0) * 0.3)} مقابل ${fmt((sot?.away ?? 0) * 0.3)}. المؤشر مبني على التسديدات على المرمى.` }]; return <div className="grid gap-4 lg:grid-cols-3">{insights.map((x) => <Card key={x.title} className="p-4" style={{ borderColor: x.accent }}><h3 className="mb-2 flex items-center gap-2 font-black text-white"><Sparkles size={16} style={{ color: x.accent }} />{x.title}</h3><p className="text-sm font-bold leading-7 text-slate-400">{x.body}</p></Card>)}</div>; }
function phaseData(events: MatchEvent[], match: MatchInfo | null) { return phases.map(([from, to]) => { const rows = events.filter((e) => eventMinute(e) >= from && eventMinute(e) < to); const home = rows.filter((e) => sideOfEvent(e, match) === 'home').reduce((s, e) => s + eventWeight(e), 0); const away = rows.filter((e) => sideOfEvent(e, match) === 'away').reduce((s, e) => s + eventWeight(e), 0); const max = Math.max(home, away, 1); return { label: `${from}-${to}`, home: home / max, away: away / max, side: home === away ? 'neutral' as Side : home > away ? 'home' as Side : 'away' as Side, intensity: Math.min(1, (home + away) / 12) }; }); }
function MatchStory({ events, match }: { events: MatchEvent[]; match: MatchInfo | null }) { const bins = phaseData(events, match); return <Card className="p-4 sm:p-5"><Title icon={<Gauge />} title="قصة المباراة حسب الفترات" /><div className="grid gap-3 sm:grid-cols-6">{bins.map((b) => <div key={b.label} className="rounded-2xl border border-white/10 bg-black/25 p-3"><b className="text-xs text-slate-400">{b.label}</b><div className="mt-3 flex h-20 items-end rounded-xl bg-white/5 p-2"><div className="w-full rounded-lg transition-all" style={{ height: `${20 + b.intensity * 60}%`, background: b.side === 'home' ? HOME : b.side === 'away' ? AWAY : '#64748b' }} /></div><p className="mt-2 truncate text-xs font-black text-white">{b.side === 'home' ? teamName(match?.homeTeam) : b.side === 'away' ? teamName(match?.awayTeam) : 'متوازن'}</p></div>)}</div></Card>; }
function MomentumChart({ events, match }: { events: MatchEvent[]; match: MatchInfo | null }) { const bins = phaseData(events, match), homePts = bins.map((b, i) => `${8 + i * 16},${50 - b.home * 10}`).join(' '), awayPts = bins.map((b, i) => `${8 + i * 16},${50 + b.away * 10}`).join(' '); return <Card className="p-4 sm:p-5"><Title icon={<Zap />} title="مؤشر الزخم" /><svg viewBox="0 0 100 60" className="h-56 w-full rounded-2xl border border-white/10 bg-black/25">{[10, 20, 30, 40, 50].map((y) => <line key={y} x1="4" x2="96" y1={y} y2={y} stroke="white" strokeOpacity=".07" />)}<line x1="4" x2="96" y1="30" y2="30" stroke="white" strokeOpacity=".2" /><polyline points={homePts} fill="none" stroke={HOME} strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" /><polyline points={awayPts} fill="none" stroke={AWAY} strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="mt-3 flex justify-center gap-3 text-xs font-bold"><span className="text-blue-300">{teamName(match?.homeTeam)}</span><span className="text-red-300">{teamName(match?.awayTeam)}</span></div></Card>; }
function Verdict({ events, match }: { events: MatchEvent[]; match: MatchInfo | null }) { if (statusKind(match?.status) !== 'finished') return null; const goals = events.filter((e) => eventIcon(e.type, e.detail) === '⚽'), counts = new Map<string, number>(); goals.forEach((g) => { const p = g.playerName || g.playerAsset?.name || 'غير محدد'; counts.set(p, (counts.get(p) || 0) + 1); }); const motm = [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] || 'غير متوفر', key = goals[0]; return <Card className="p-5"><Title icon={<Trophy />} title="الحكم النهائي" /><div className="grid gap-3 md:grid-cols-2"><ScoreBox label="رجل المباراة" value={motm} color="text-yellow-200" /><ScoreBox label="اللحظة المفتاحية" value={key ? `${key.minuteLabel || key.minute || '—'} · ${key.playerName || key.detail || 'الهدف الأول'}` : 'غير متوفر'} color="text-emerald-200" /></div></Card>; }
function LiveTicker({ events }: { events: MatchEvent[] }) { const latest = [...events].sort((a, b) => eventMinute(b) - eventMinute(a)).slice(0, 3); if (!latest.length) return null; return <Card className="overflow-hidden p-3"><div className="flex animate-pulse gap-3 overflow-hidden text-xs font-black text-slate-200">{latest.map((e) => <span key={e.id} className="shrink-0 rounded-full border border-white/10 bg-black/25 px-3 py-2">{eventIcon(e.type, e.detail)} {e.minuteLabel || e.minute || '—'} · {e.playerName || e.detail || 'حدث'}</span>)}</div></Card>; }
function Overview({ stats, events, match }: { stats: StatRow[]; events: MatchEvent[]; match: MatchInfo }) { const top = stats.filter((s) => s.home !== null || s.away !== null).slice(0, 4); return <div className="space-y-5"><div className="grid gap-4 lg:grid-cols-4">{top.map((s) => <ScoreBox key={s.key} label={s.label} value={`${fmt(s.home, s.suffix)} - ${fmt(s.away, s.suffix)}`} color="text-white" />)}</div><div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><PitchMap events={events} match={match} /><EventsTimeline events={events.slice(-8)} match={match} /></div><Intelligence stats={stats} match={match} /><Verdict events={events} match={match} /></div>; }

export default function MatchDataPanel({ matchId, dbMatchId }: Props) {
  const [match, setMatch] = useState<MatchInfo | null>(null), [latest, setLatest] = useState<Snapshot | null>(null), [history, setHistory] = useState<Snapshot[]>([]), [events, setEvents] = useState<MatchEvent[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [active, setActive] = useState<TabId>('overview');
  const query = useMemo(() => { const p = new URLSearchParams(); if (matchId !== null && matchId !== undefined && matchId !== '') p.set('matchId', String(matchId)); if (dbMatchId !== null && dbMatchId !== undefined && dbMatchId !== '') p.set('dbMatchId', String(dbMatchId)); return p.toString(); }, [matchId, dbMatchId]);
  const fetchStats = useCallback(async () => { if (!query) throw new Error('معرّف المباراة غير متوفر'); const res = await fetch(`/api/matches/live-stats?${query}`, { cache: 'no-store' }); const data = (await res.json()) as StatsResponse; if (!res.ok || !data.ok || !data.match) throw new Error('تعذر تحميل بيانات المباراة'); setMatch(data.match); setLatest(data.latest || null); setHistory(Array.isArray(data.history) ? data.history : []); }, [query]);
  const fetchEvents = useCallback(async () => { if (!query) return; const res = await fetch(`/api/matches/live-events?${query}`, { cache: 'no-store' }); const data = (await res.json()) as EventsResponse; if (res.ok && data.ok) setEvents(Array.isArray(data.events) ? data.events : []); }, [query]);
  const loadAll = useCallback(async () => { setError(null); try { await Promise.all([fetchStats(), fetchEvents()]); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'حدث خطأ غير متوقع'); } finally { setLoading(false); } }, [fetchEvents, fetchStats]);
  useEffect(() => { setLoading(true); void loadAll(); const statsTimer = window.setInterval(() => { void fetchStats().catch(() => undefined); }, 30000); const eventsTimer = window.setInterval(() => { void fetchEvents().catch(() => undefined); }, 15000); return () => { window.clearInterval(statsTimer); window.clearInterval(eventsTimer); }; }, [loadAll, fetchStats, fetchEvents]);
  const snapshots = useMemo(() => [latest, ...history].filter((s): s is Snapshot => Boolean(s)), [latest, history]);
  const computedStats = useMemo(() => statDefs.map((def) => readStat(def, snapshots)).sort((a, b) => statPriority.indexOf(a.key) - statPriority.indexOf(b.key)), [snapshots]);
  const visibleStats = useMemo(() => computedStats.filter((s) => s.home !== null || s.away !== null), [computedStats]);
  const h2h = useMemo(() => h2hRows(snapshots), [snapshots]);
  const homeLast = useMemo(() => lastRows(snapshots, 'home'), [snapshots]);
  const awayLast = useMemo(() => lastRows(snapshots, 'away'), [snapshots]);
  const standings = useMemo(() => standingRows(snapshots), [snapshots]);
  const counts = useMemo(() => ({ stats: visibleStats.length, events: events.length, history: h2h.length + homeLast.length + awayLast.length, group: standings.length }), [visibleStats.length, events.length, h2h.length, homeLast.length, awayLast.length, standings.length]);
  if (loading) return <Spinner />;
  if (error) return <div className="flex min-h-[65vh] items-center justify-center bg-slate-950 p-4 text-white" dir="rtl"><Card className="max-w-md p-6 text-center"><AlertTriangle className="mx-auto mb-3 text-red-400" /><h2 className="text-xl font-black">تعذر تحميل مركز المباراة</h2><p className="mt-2 text-sm text-slate-400">{error}</p><button onClick={() => void loadAll()} className="mt-5 inline-flex items-center gap-2 rounded-2xl bg-blue-500 px-5 py-3 text-sm font-black text-white"><RefreshCw size={15} /> إعادة المحاولة</button></Card></div>;
  if (!match) return null;
  const statsToShow = visibleStats.length ? visibleStats : computedStats;
  return <main dir="rtl" className="min-h-screen bg-slate-950 px-3 py-4 text-white [background-image:radial-gradient(circle_at_top_left,rgba(59,130,246,.16),transparent_28%),radial-gradient(circle_at_bottom_right,rgba(239,68,68,.14),transparent_30%)] sm:px-5 lg:px-8"><div className="mx-auto max-w-7xl space-y-5"><LiveTicker events={events} /><Hero match={match} /><Tabs active={active} setActive={setActive} counts={counts} />{active === 'overview' ? <Overview stats={statsToShow} events={events} match={match} /> : null}{active === 'stats' ? <StatsPanel stats={statsToShow} /> : null}{active === 'pitch' ? <PitchMap events={events} match={match} /> : null}{active === 'events' ? <EventsTimeline events={events} match={match} /> : null}{active === 'momentum' ? <div className="grid gap-5 xl:grid-cols-2"><MatchStory events={events} match={match} /><MomentumChart events={events} match={match} /><div className="xl:col-span-2"><Intelligence stats={computedStats} match={match} /></div></div> : null}{active === 'history' ? <div className="space-y-5"><H2H rows={h2h} match={match} /><LastMatches home={homeLast} away={awayLast} match={match} /></div> : null}{active === 'group' ? <Standings rows={standings} match={match} /> : null}</div></main>;
}
