'use client';

import { useState } from 'react';
import Link from 'next/link';

const labels: Record<string, string> = { matchSummary: 'ملخص المباراة', tacticalReading: 'القراءة التكتيكية', statsAnalysis: 'تحليل الإحصاءات', turningPoints: 'نقاط التحول', playerAnalysis: 'تحليل اللاعبين', groupImpact: 'أثر النتيجة', conclusion: 'الخلاصة' };

export default function MatchArticleEditor({ article }: { article: any }) {
  const [form, setForm] = useState({ title: article.title || '', metaTitle: article.metaTitle || '', metaDescription: article.metaDescription || '', excerpt: article.excerpt || '', sections: Object.fromEntries(Object.keys(labels).map((key) => [key, article.sections?.[key] || ''])) });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [status, setStatus] = useState(article.status);
  const change = (key: string, value: string) => setForm((old) => ({ ...old, [key]: value }));
  const changeSection = (key: string, value: string) => setForm((old) => ({ ...old, sections: { ...old.sections, [key]: value } }));
  async function submit(action: 'save' | 'publish' | 'request_review') { setBusy(true); setMessage(''); try { const res = await fetch(`/api/admin/match-articles/${article.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, action, confirmReviewed: action === 'publish' }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'تعذر الحفظ'); setStatus(data.article.status); setMessage(action === 'publish' ? 'تم اعتماد المقال ونشره.' : 'تم حفظ التعديلات.'); } catch (error: any) { setMessage(error.message); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#06110d] px-3 py-6 text-white" dir="rtl"><div className="mx-auto max-w-5xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-white/10 bg-white/[0.05] p-5"><div><span className="text-xs font-black text-[#18E58F]">{status}</span><h1 className="mt-1 text-2xl font-black">محرر المقال</h1></div><Link href="/admin/match-articles" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black">العودة للقائمة</Link></header><section className="space-y-4 rounded-3xl border border-white/10 bg-black/20 p-5"><label className="block"><span className="text-xs font-black text-slate-400">العنوان</span><input value={form.title} onChange={(e) => change('title', e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 outline-none focus:border-[#18E58F]" /></label><div className="grid gap-4 md:grid-cols-2"><label><span className="text-xs font-black text-slate-400">SEO Title</span><input value={form.metaTitle} onChange={(e) => change('metaTitle', e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3" /></label><label><span className="text-xs font-black text-slate-400">Meta Description</span><textarea value={form.metaDescription} onChange={(e) => change('metaDescription', e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3" /></label></div><label className="block"><span className="text-xs font-black text-slate-400">المقتطف</span><textarea value={form.excerpt} onChange={(e) => change('excerpt', e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-white/10 bg-black/30 p-3" /></label>{Object.entries(labels).map(([key, label]) => <label key={key} className="block"><span className="text-xs font-black text-[#F8C846]">{label}</span><textarea value={(form.sections as any)[key]} onChange={(e) => changeSection(key, e.target.value)} className="mt-2 min-h-48 w-full rounded-xl border border-white/10 bg-black/30 p-3 leading-8" /></label>)}</section>{message && <p className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-bold">{message}</p>}<footer className="sticky bottom-3 flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-[#06110d]/95 p-3 backdrop-blur"><button disabled={busy} onClick={() => submit('save')} className="rounded-xl border border-white/10 px-5 py-3 text-sm font-black disabled:opacity-50">حفظ كمسودة</button><button disabled={busy} onClick={() => submit('request_review')} className="rounded-xl bg-[#F8C846] px-5 py-3 text-sm font-black text-black disabled:opacity-50">إعادة للمراجعة</button><button disabled={busy} onClick={() => submit('publish')} className="rounded-xl bg-[#18E58F] px-5 py-3 text-sm font-black text-black disabled:opacity-50">اعتماد ونشر</button></footer></div></main>;
}
