import type { GroupAFbrefRosterPlayer } from './groupAFbrefStats';

export type ManualFbrefRosterSnapshot = {
  team: string;
  teamCode: string;
  teamCodes: string[];
  sourceUrl: string;
  roster: GroupAFbrefRosterPlayer[];
};

export const manualFbrefRosterSnapshots: ManualFbrefRosterSnapshot[] = [
  {
    "team": "Croatia",
    "teamCode": "CRO",
    "teamCodes": [
      "CRO",
      "HR",
      "CROATIA"
    ],
    "sourceUrl": "FBref copied roster text uploaded by platform owner",
    "roster": [
      {
        "number": "16",
        "player": "Martin Baturina",
        "pos": "MF",
        "club": "Como",
        "clubRaw": "1.it Como",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Zürich, Switzerland",
        "birthDate": "2003-02-16",
        "age": "23-115",
        "ageYears": 23,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "11",
        "player": "Ante Budimir",
        "pos": "FW",
        "club": "Osasuna",
        "clubRaw": "1.es Osasuna",
        "clubCountry": null,
        "clubCountryCode": "es",
        "birthPlace": "Zenica, Bosnia and Herzegovina",
        "birthDate": "1991-07-22",
        "age": "34-324",
        "ageYears": 34,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "5",
        "player": "Duje Ćaleta-Car",
        "pos": "DF",
        "club": "Real Sociedad",
        "clubRaw": "1.es Real Sociedad",
        "clubCountry": null,
        "clubCountryCode": "es",
        "birthPlace": "Grad Šibenik, Croatia",
        "birthDate": "1996-09-17",
        "age": "29-267",
        "ageYears": 29,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "25",
        "player": "Martin Erlić",
        "pos": "DF",
        "club": "Midtjylland",
        "clubRaw": "1.dk Midtjylland",
        "clubCountry": null,
        "clubCountryCode": "dk",
        "birthPlace": "Zadar, Croatia",
        "birthDate": "1998-01-24",
        "age": "28-138",
        "ageYears": 28,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "19",
        "player": "Toni Fruk",
        "pos": "FW,MF",
        "club": "Rijeka",
        "clubRaw": "1.hr Rijeka",
        "clubCountry": null,
        "clubCountryCode": "hr",
        "birthPlace": "Grad Našice, Croatia",
        "birthDate": "2001-03-09",
        "age": "25-094",
        "ageYears": 25,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "4",
        "player": "Joško Gvardiol",
        "pos": "DF",
        "club": "Manchester City",
        "clubRaw": "1.eng Manchester City",
        "clubCountry": null,
        "clubCountryCode": "eng",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "2002-01-23",
        "age": "24-139",
        "ageYears": 24,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "18",
        "player": "Kristijan Jakić",
        "pos": "DF,MF",
        "club": "Augsburg",
        "clubRaw": "1.de Augsburg",
        "clubCountry": null,
        "clubCountryCode": "de",
        "birthPlace": "Grad Split, Croatia",
        "birthDate": "1997-05-14",
        "age": "29-028",
        "ageYears": 29,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "23",
        "player": "Dominik Kotarski",
        "pos": "GK",
        "club": "FC Copenhagen",
        "clubRaw": "1.dk FC Copenhagen",
        "clubCountry": null,
        "clubCountryCode": "dk",
        "birthPlace": "Zabok, Croatia",
        "birthDate": "2000-02-10",
        "age": "26-121",
        "ageYears": 26,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "8",
        "player": "Mateo Kovačić",
        "pos": "MF",
        "club": "Manchester City",
        "clubRaw": "1.eng Manchester City",
        "clubCountry": null,
        "clubCountryCode": "eng",
        "birthPlace": "Linz, Austria",
        "birthDate": "1994-05-06",
        "age": "32-036",
        "ageYears": 32,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "9",
        "player": "Andrej Kramarić",
        "pos": "FW,MF",
        "club": "Hoffenheim",
        "clubRaw": "1.de Hoffenheim",
        "clubCountry": null,
        "clubCountryCode": "de",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "1991-06-19",
        "age": "34-357",
        "ageYears": 34,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "1",
        "player": "Dominik Livaković",
        "pos": "GK",
        "club": "Dinamo Zagreb",
        "clubRaw": "1.hr Dinamo Zagreb",
        "clubCountry": null,
        "clubCountryCode": "hr",
        "birthPlace": "Zadar, Croatia",
        "birthDate": "1995-01-09",
        "age": "31-153",
        "ageYears": 31,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "20",
        "player": "Igor Matanović",
        "pos": "FW",
        "club": "Freiburg",
        "clubRaw": "1.de Freiburg",
        "clubCountry": null,
        "clubCountryCode": "de",
        "birthPlace": "Hamburg, Germany",
        "birthDate": "2003-03-31",
        "age": "23-072",
        "ageYears": 23,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "10",
        "player": "Luka Modrić",
        "pos": "MF",
        "club": "Milan",
        "clubRaw": "1.it Milan",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Zadar, Croatia",
        "birthDate": "1985-09-09",
        "age": "40-275",
        "ageYears": 40,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "7",
        "player": "Nikola Moro",
        "pos": "MF",
        "club": "Bologna",
        "clubRaw": "1.it Bologna",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Grad Split, Croatia",
        "birthDate": "1998-03-12",
        "age": "28-091",
        "ageYears": 28,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "26",
        "player": "Petar Musa",
        "pos": "FW",
        "club": "FC Dallas",
        "clubRaw": "1.us FC Dallas",
        "clubCountry": null,
        "clubCountryCode": "us",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "1998-03-04",
        "age": "28-099",
        "ageYears": 28,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "12",
        "player": "Ivor Pandur",
        "pos": "GK",
        "club": "Hull City",
        "clubRaw": "2.eng Hull City",
        "clubCountry": null,
        "clubCountryCode": "eng",
        "birthPlace": "Sušak, Croatia",
        "birthDate": "2000-03-25",
        "age": "26-078",
        "ageYears": 26,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "24",
        "player": "Marco Pašalić",
        "pos": "MF",
        "club": "Orlando City",
        "clubRaw": "1.us Orlando City",
        "clubCountry": null,
        "clubCountryCode": "us",
        "birthPlace": "Karlsruhe, Germany",
        "birthDate": "2000-09-14",
        "age": "25-270",
        "ageYears": 25,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "15",
        "player": "Mario Pašalić",
        "pos": "FW,MF",
        "club": "Atalanta",
        "clubRaw": "1.it Atalanta",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Mainz, Germany",
        "birthDate": "1995-02-09",
        "age": "31-122",
        "ageYears": 31,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "14",
        "player": "Ivan Perišić",
        "pos": "FW,MF",
        "club": "PSV Eindhoven",
        "clubRaw": "1.nl PSV Eindhoven",
        "clubCountry": null,
        "clubCountryCode": "nl",
        "birthPlace": "Split, Croatia",
        "birthDate": "1989-02-02",
        "age": "37-129",
        "ageYears": 37,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "3",
        "player": "Marin Pongračić",
        "pos": "DF",
        "club": "Fiorentina",
        "clubRaw": "1.it Fiorentina",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Landshut, Germany",
        "birthDate": "1997-09-11",
        "age": "28-273",
        "ageYears": 28,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "13",
        "player": "Marco Pjaca",
        "pos": "FW,MF",
        "club": "Dinamo Zagreb",
        "clubRaw": "1.hr Dinamo Zagreb",
        "clubCountry": null,
        "clubCountryCode": "hr",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "1995-05-06",
        "age": "31-036",
        "ageYears": 31,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "21",
        "player": "Borna Sosa",
        "pos": "DF,MF",
        "club": "Crystal Palace",
        "clubRaw": "1.eng Crystal Palace",
        "clubCountry": null,
        "clubCountryCode": "eng",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "1998-01-21",
        "age": "28-141",
        "ageYears": 28,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "2",
        "player": "Josip Stanišić",
        "pos": "DF",
        "club": "Bayern Munich",
        "clubRaw": "1.de Bayern Munich",
        "clubCountry": null,
        "clubCountryCode": "de",
        "birthPlace": "München, Germany",
        "birthDate": "2000-04-02",
        "age": "26-070",
        "ageYears": 26,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "17",
        "player": "Petar Sučić",
        "pos": "MF",
        "club": "Inter",
        "clubRaw": "1.it Inter",
        "clubCountry": null,
        "clubCountryCode": "it",
        "birthPlace": "Livno, Bosnia and Herzegovina",
        "birthDate": "2003-10-25",
        "age": "22-229",
        "ageYears": 22,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "22",
        "player": "Dion Drena Beljo",
        "pos": "FW",
        "club": "Dinamo Zagreb",
        "clubRaw": "1.hr Dinamo Zagreb",
        "clubCountry": null,
        "clubCountryCode": "hr",
        "birthPlace": "Zagreb, Croatia",
        "birthDate": "2002-03-01",
        "age": "24-102",
        "ageYears": 24,
        "mp": null,
        "minutes": null,
        "goals": null
      },
      {
        "number": "6",
        "player": "Martin Zubimendi",
        "pos": "MF",
        "club": "Real Sociedad",
        "clubRaw": "1.es Real Sociedad",
        "clubCountry": null,
        "clubCountryCode": "es",
        "birthPlace": "Donostia-San Sebastián, Spain",
        "birthDate": "1999-02-02",
        "age": "27-129",
        "ageYears": 27,
        "mp": null,
        "minutes": null,
        "goals": null
      }
    ]
  }
] satisfies ManualFbrefRosterSnapshot[];
