import { Prisma, PrismaClient } from '@prisma/client';
import { normalizeTeamReportBody } from './teamReportFormat';

type Standing = { rank: number; squad: string; mp: number; wins: number; draws: number; losses: number; gf: number; ga: number; gd: string; pts: number; last5: string };
type Match = { date: string; time: string; competition: string; round: string; venue: string; result: string; gf: string; ga: string; opponent: string; possession: number | null; attendance: number | null; captain: string; formation: string; opponentFormation: string; referee: string; notes: string };
type RosterSummary = { count: number; averageAge: number; topClubs: string[] };
type TeamSnapshot = { team: string; teamCode: string; teamCodes: string[]; group: 'G' | 'H' | 'I'; sourceUrl: string; rosterSummary: RosterSummary; standing: Standing; worldCupMatches: Match[] };

const arabicTeamNames: Record<string, string> = {
  EGY: 'مصر', IRN: 'إيران', NZL: 'نيوزيلندا', BEL: 'بلجيكا',
  KSA: 'السعودية', ESP: 'إسبانيا', URU: 'أوروغواي', CPV: 'الرأس الأخضر',
  FRA: 'فرنسا', IRQ: 'العراق', NOR: 'النرويج', SEN: 'السنغال',
};

function displayTeam(stats: TeamSnapshot) { return arabicTeamNames[stats.teamCode] || stats.team; }
function n(value: number | null | undefined) { return typeof value === 'number' && Number.isFinite(value) ? value.toLocaleString('ar-EG') : 'غير متوفر في المصادر'; }
function opponentName(raw: string) { return raw.replace(/^[a-z]{2}\s+/i, '').trim(); }
function upcomingMatches(stats: TeamSnapshot) { return stats.worldCupMatches.map((match) => `${match.date} ضد ${opponentName(match.opponent)}`).join('؛ '); }

function buildSummary(stats: TeamSnapshot) {
  return `${displayTeam(stats)} لديه لقطة FBref قبل أول مباراة في المجموعة ${stats.group}: ${n(stats.rosterSummary.count)} لاعبًا في القائمة المتاحة، متوسط عمر ${n(stats.rosterSummary.averageAge)} سنة، والمباريات المسجلة في المصدر: ${upcomingMatches(stats)}.`;
}

function buildReportBody(stats: TeamSnapshot) {
  const teamName = displayTeam(stats);
  return `بطاقة المنتخب: ${teamName} — المجموعة ${stats.group} — مصدر البيانات FBref copied source text. هذه لقطة قبل لعب مباريات المجموعة في المصدر، لذلك لا توجد أرقام تسديد أو حراسة أو استحواذ فعلية بعد.

القائمة الحالية وبنية الفريق: تضم القائمة المتاحة في FBref ${n(stats.rosterSummary.count)} لاعبًا، بمتوسط عمر تقريبي ${n(stats.rosterSummary.averageAge)} سنة. أكثر الأندية حضورًا: ${stats.rosterSummary.topClubs.join('، ') || 'غير متوفر في المصادر'}.

وضع المنتخب في المجموعة قبل البداية: المركز الترتيبي داخل جدول FBref ${n(stats.standing.rank)}، لعب ${n(stats.standing.mp)}، فاز ${n(stats.standing.wins)}، تعادل ${n(stats.standing.draws)}، خسر ${n(stats.standing.losses)}، له ${n(stats.standing.gf)}، عليه ${n(stats.standing.ga)}، فارق ${stats.standing.gd}، نقاط ${n(stats.standing.pts)}.

المباريات المسجلة في المصدر: ${upcomingMatches(stats) || 'غير متوفر في المصادر'}.

مؤشرات غير متوفرة بعد: التسديدات، التسديدات على المرمى، الأهداف في البطولة، الحراسة، التصديات، الاستحواذ، التشكيلات المستخدمة، والبطاقات. السبب: لا توجد مباراة مكتملة داخل لقطة FBref لهذه المجموعة وقت النسخ.

سجل المصادر: لقطة إحصائية من FBref copy/paste source text أرسلها مالك المنصة، وليست مصدرًا رسميًا للقائمة. عند اختلافها مع FIFA Squad Lists يتم اعتماد FIFA للقائمة الرسمية، واستخدام FBref للإحصاءات والمطابقة.`;
}

export const groupGHIFbrefStats: TeamSnapshot[] = [
  { team: 'Egypt', teamCode: 'EGY', teamCodes: ['EGY','EG','EGYPT'], group: 'G', sourceUrl: 'https://fbref.com/en/squads/b8889750/2026/c1/Egypt-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 28.7, topClubs: ['Al Ahly (8)','Zamalek SC (3)','Pyramids FC (3)','ZED (2)','Barcelona B (1)'] }, standing: { rank: 2, squad: 'eg Egypt', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'D W D W L' }, worldCupMatches: [{ date: '2026-06-15', time: '12:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'be Belgium', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'nz New Zealand', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '20:00 (06:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'ir IR Iran', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'IR Iran', teamCode: 'IRN', teamCodes: ['IRN','IR','IR IRAN','IRAN'], group: 'G', sourceUrl: 'https://fbref.com/en/squads/6a08f71e/2026/c1/IR-Iran-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 29.8, topClubs: ['Persepolis (4)','Tractor (4)','Esteghlal (3)','Sepahan (3)','Al-Ittihad Kalba SC (2)'] }, standing: { rank: 3, squad: 'ir IR Iran', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W L W W W' }, worldCupMatches: [{ date: '2026-06-15', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'nz New Zealand', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '12:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'be Belgium', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '20:00 (06:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'eg Egypt', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'New Zealand', teamCode: 'NZL', teamCodes: ['NZL','NZ','NEW ZEALAND'], group: 'G', sourceUrl: 'https://fbref.com/en/squads/259855f0/2026/c1/New-Zealand-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 27.6, topClubs: ['Auckland FC (5)','Wellington Phoenix (3)','Western Sydney Wanderers (1)','Newcastle Jets (1)','Viking (1)'] }, standing: { rank: 4, squad: 'nz New Zealand', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'D L L L L' }, worldCupMatches: [{ date: '2026-06-15', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'ir IR Iran', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'eg Egypt', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'be Belgium', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Belgium', teamCode: 'BEL', teamCodes: ['BEL','BE','BELGIUM'], group: 'G', sourceUrl: 'https://fbref.com/en/squads/361422b9/2026/c1/Belgium-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 27.1, topClubs: ['Lille (3)','Club Brugge (3)','Napoli (2)','Milan (2)','Strasbourg (2)'] }, standing: { rank: 1, squad: 'be Belgium', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W W D W W' }, worldCupMatches: [{ date: '2026-06-15', time: '12:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'eg Egypt', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '12:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'ir IR Iran', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '18:00 (04:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'nz New Zealand', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Saudi Arabia', teamCode: 'KSA', teamCodes: ['KSA','SA','SAUDI ARABIA'], group: 'H', sourceUrl: 'https://fbref.com/en/squads/6e84edac/2026/c1/Saudi-Arabia-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 28.0, topClubs: ['Al-Hilal (7)','Al-Nassr (6)','Al-Qadsiah (4)','Al-Ahli (3)','Al-Ittihad (2)'] }, standing: { rank: 1, squad: 'sa Saudi Arabia', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'L L L W D' }, worldCupMatches: [{ date: '2026-06-15', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'uy Uruguay', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '12:00 (19:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'es Spain', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '19:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'cv Cape Verde', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Spain', teamCode: 'ESP', teamCodes: ['ESP','ES','SPAIN'], group: 'H', sourceUrl: 'https://fbref.com/en/squads/b561dd30/2026/c1/Spain-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 26.2, topClubs: ['Barcelona (8)','Atlético Madrid (3)','Athletic Club (3)','Arsenal (3)','Chelsea (1)'] }, standing: { rank: 2, squad: 'es Spain', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'D W D D W' }, worldCupMatches: [{ date: '2026-06-15', time: '12:00 (19:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'cv Cape Verde', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '12:00 (19:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sa Saudi Arabia', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '18:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'uy Uruguay', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Uruguay', teamCode: 'URU', teamCodes: ['URU','UY','URUGUAY'], group: 'H', sourceUrl: 'https://fbref.com/en/squads/870e020f/2026/c1/Uruguay-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 28.2, topClubs: ['Flamengo (4)','América (3)','Palmeiras (2)','Sporting CP (1)','Barcelona (1)'] }, standing: { rank: 3, squad: 'uy Uruguay', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W D L D D' }, worldCupMatches: [{ date: '2026-06-15', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sa Saudi Arabia', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'cv Cape Verde', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '18:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'es Spain', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Cape Verde', teamCode: 'CPV', teamCodes: ['CPV','CV','CAPE VERDE'], group: 'H', sourceUrl: 'https://fbref.com/en/squads/31fa6fa6/2026/c1/Cape-Verde-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 29.2, topClubs: ['Vitória Guimarães (1)','FK Akron Tolyatti (1)','Estrela (1)','Villarreal (1)','Başakşehir (1)'] }, standing: { rank: 4, squad: 'cv Cape Verde', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W D W W W' }, worldCupMatches: [{ date: '2026-06-15', time: '12:00 (19:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'es Spain', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-21', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'uy Uruguay', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '19:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sa Saudi Arabia', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'France', teamCode: 'FRA', teamCodes: ['FRA','FR','FRANCE'], group: 'I', sourceUrl: 'https://fbref.com/en/squads/b1b36dcd/2026/c1/France-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 26.6, topClubs: ['Paris Saint-Germain (5)','Crystal Palace (2)','Milan (2)','Real Madrid (2)','Bayern Munich (2)'] }, standing: { rank: 1, squad: 'fr France', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W W W L W' }, worldCupMatches: [{ date: '2026-06-16', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sn Senegal', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-22', time: '17:00 (00:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'iq Iraq', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'no Norway', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Iraq', teamCode: 'IRQ', teamCodes: ['IRQ','IQ','IRAQ'], group: 'I', sourceUrl: 'https://fbref.com/en/squads/ec843efd/2026/c1/Iraq-Men-Stats-World-Cup', rosterSummary: { count: 23, averageAge: 26.2, topClubs: ['Al-Shorta (2)', "Al-Zawra'a SC (2)", 'Al-Karma (2)', 'Al-Talaba (2)', 'Pogoń Szczecin (1)'] }, standing: { rank: 2, squad: 'iq Iraq', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W W W D L' }, worldCupMatches: [{ date: '2026-06-16', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'no Norway', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-22', time: '17:00 (00:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'fr France', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sn Senegal', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Norway', teamCode: 'NOR', teamCodes: ['NOR','NO','NORWAY'], group: 'I', sourceUrl: 'https://fbref.com/en/squads/599eba19/2026/c1/Norway-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 26.3, topClubs: ['Bodø/Glimt (3)','Benfica (2)','Fulham (2)','Rangers (1)','Brentford (1)'] }, standing: { rank: 3, squad: 'no Norway', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W L D W D' }, worldCupMatches: [{ date: '2026-06-16', time: '18:00 (01:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'iq Iraq', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-22', time: '20:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'sn Senegal', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'fr France', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
  { team: 'Senegal', teamCode: 'SEN', teamCodes: ['SEN','SN','SENEGAL'], group: 'I', sourceUrl: 'https://fbref.com/en/squads/9ab5c684/2026/c1/Senegal-Men-Stats-World-Cup', rosterSummary: { count: 26, averageAge: 26.6, topClubs: ['Monaco (2)','Nice (2)','Everton (2)','Bayern Munich (2)','Rayo Vallecano (1)'] }, standing: { rank: 4, squad: 'sn Senegal', mp: 0, wins: 0, draws: 0, losses: 0, gf: 0, ga: 0, gd: '0', pts: 0, last5: 'W W W L D' }, worldCupMatches: [{ date: '2026-06-16', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'fr France', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-22', time: '20:00 (03:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'no Norway', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }, { date: '2026-06-26', time: '15:00 (22:00)', competition: 'World Cup', round: 'Group stage', venue: 'Neutral', result: '', gf: '', ga: '', opponent: 'iq Iraq', possession: null, attendance: null, captain: '', formation: '', opponentFormation: '', referee: '', notes: '' }] },
];

export function findGroupGHIFbrefStats(identifier?: string | null) {
  const normalized = String(identifier || '').trim().toLowerCase();
  if (!normalized) return null;
  return groupGHIFbrefStats.find((stats) => stats.teamCode.toLowerCase() === normalized || stats.team.toLowerCase() === normalized || stats.teamCodes.some((code) => code.toLowerCase() === normalized)) || null;
}

export function toTeamFBRefStats(stats: TeamSnapshot) {
  return {
    available: true,
    exportedAt: '2026-06-15T00:00:00.000Z',
    sourceUrl: stats.sourceUrl,
    standing: { group: stats.group, rank: String(stats.standing.rank), mp: stats.standing.mp, wins: stats.standing.wins, draws: stats.standing.draws, losses: stats.standing.losses, gf: stats.standing.gf, ga: stats.standing.ga, gd: stats.standing.gd, pts: stats.standing.pts },
    shooting: null,
    goalkeeping: null,
    misc: null,
    matchContext: { completedCount: 0, upcomingCount: stats.worldCupMatches.length, formations: [], averagePossession: null },
    roster: stats.rosterSummary,
    standard: { usedPlayers: 0, scorers: [], assisters: [], minutesLeaders: [] },
  };
}

async function seedReportsForGroup(prisma: PrismaClient, group: 'G' | 'H' | 'I') {
  let created = 0;
  let skipped = 0;
  const missingTeams: string[] = [];
  const teams = await prisma.asset.findMany({ where: { type: 'TEAM' }, select: { id: true, name: true, code: true } });
  for (const stats of groupGHIFbrefStats.filter((item) => item.group === group)) {
    const team = teams.find((candidate) => stats.teamCodes.some((code) => String(candidate.code || '').toLowerCase() === code.toLowerCase()) || String(candidate.name || '').toLowerCase() === stats.team.toLowerCase());
    if (!team) { skipped++; missingTeams.push(stats.teamCodes.join('/')); continue; }
    const title = `FBref Snapshot — ${displayTeam(stats)} — World Cup 2026`;
    const normalized = normalizeTeamReportBody({ teamName: team.name, title, summary: buildSummary(stats), body: buildReportBody(stats), sourceName: 'FBref copied source text — 2026 World Cup', sourceUrl: stats.sourceUrl });
    const metrics: Prisma.InputJsonValue = { model: `fbref-copy-source-group-${group.toLowerCase()}-prematch-v1`, source: 'FBref copied source text', exportedAt: '2026-06-15T00:00:00.000Z', teamCode: stats.teamCode, group: stats.group, standing: stats.standing, rosterSummary: stats.rosterSummary, worldCupMatches: stats.worldCupMatches, note: 'Pre-match snapshot: no completed World Cup match in this FBref copy.' };
    const report = await prisma.teamIntelligenceReport.findFirst({ where: { teamId: team.id, title, provider: 'FBREF_STATHEAD_SNAPSHOT' }, select: { id: true } });
    if (report) { skipped++; continue; }
    await prisma.teamIntelligenceReport.create({ data: { teamId: team.id, title, summary: buildSummary(stats), body: normalized.body, reportType: 'TEAM_PROFILE', language: 'ar', sourceName: 'FBref copied source text — 2026 World Cup', sourceUrl: stats.sourceUrl, sourceCategory: 'stats', confidence: 'B', provider: 'FBREF_STATHEAD_SNAPSHOT', metrics, tacticalTags: ['FBref', 'World Cup 2026', `Group ${group}`, 'prematch', 'copied-source'], strengths: [`قائمة FBref متاحة: ${n(stats.rosterSummary.count)} لاعبًا`, `متوسط عمر تقريبي: ${n(stats.rosterSummary.averageAge)} سنة`], weaknesses: ['لا توجد مباراة مكتملة في هذه اللقطة، لذلك لا تتوفر أرقام تسديد أو حراسة أو استحواذ فعلية'], lastCheckedAt: new Date(), publishedAt: new Date() } });
    created++;
  }
  return { created, skipped, missingTeams, total: groupGHIFbrefStats.filter((item) => item.group === group).length };
}

export function seedGroupGFbrefReports(prisma: PrismaClient) { return seedReportsForGroup(prisma, 'G'); }
export function seedGroupHFbrefReports(prisma: PrismaClient) { return seedReportsForGroup(prisma, 'H'); }
export function seedGroupIFbrefReports(prisma: PrismaClient) { return seedReportsForGroup(prisma, 'I'); }
