import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getTeamVisualTheme } from '@/lib/teamVisualThemes';
import { animationEventLabel, inferLiveAnimationSpatial, normalizeAnimationEventType, type AnimationTeamSide } from '@/lib/liveAnimationSpatial';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const revalidate = 0;

type RouteContext = { params: Promise<{ id: string }> };
type MetricView = { key: string; label: string; home: number | null; away: number | null; suffix?: string; source?: string; available: boolean };

const LIVE_STATUSES = ['LIVE', 'IN_PLAY', '1H', '2H', 'ET', 'P', 'PAUSED'];
const HALF_TIME_STATUSES = ['HT', 'HALFTIME', 'HALF_TIME', 'BREAK'];
const FINISHED_STATUSES = ['FINISHED', 'FT', 'AET', 'PEN', 'COMPLETED', 'ENDED', 'FINAL_VERIFIED'];
const KICKOFF_GRACE_MINUTES = 3;
const SOFT_LIVE_MAX_MINUTES = 140;
const METRIC_DEFS: Array<[string, string, string?]> = [
  ['possession', 'الاستحواذ', '%'], ['xg', 'الأهداف المتوقعة xG'], ['npxg', 'xG بدون ركلات جزاء'], ['bigChances', 'فرص كبيرة'],
  ['shots', 'التسديدات'], ['shotsOnTarget', 'على المرمى'], ['shotsOffTarget', 'خارج المرمى'], ['blockedShots', 'تسديدات محجوبة'], ['shotsInsideBox', 'داخل المنطقة'], ['shotsOutsideBox', 'خارج المنطقة'],
  ['corners', 'الركنيات'], ['fouls', 'الأخطاء'], ['offsides', 'التسللات'], ['yellowCards', 'بطاقات صفراء'], ['redCards', 'بطاقات حمراء'],
  ['passes', 'التمريرات'], ['accuratePasses', 'تمريرات صحيحة'], ['tackles', 'تدخلات'], ['interceptions', 'اعتراضات'], ['clearances', 'تشتيت'], ['ballRecoveries', 'استرجاع الكرة'], ['saves', 'تصديات الحارس'],
  ['attacks', 'الهجمات'], ['dangerousAttacks', 'هجمات خطيرة'],
];
const COLUMN_KEYS: Record<string, [string, string]> = {
  possession: ['homePossession', 'awayPossession'], attacks: ['homeAttacks', 'awayAttacks'], dangerousAttacks: ['homeDangerousAttacks', 'awayDangerousAttacks'],
  shots: ['homeShots', 'awayShots'], shotsOnTarget: ['homeShotsOnTarget', 'awayShotsOnTarget'], shotsOffTarget: ['homeShotsOffTarget', 'awayShotsOffTarget'],
  corners: ['homeCorners', 'awayCorners'], yellowCards: ['homeYellowCards', 'awayYellowCards'], redCards: ['homeRedCards', 'awayRedCards'], saves: ['homeSaves', 'awaySaves'],
};

function safeNumber(value: any, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }
function toNullableNumber(value: any) { if (value === null || value === undefined || value === '') return null; const number = Number(typeof value === 'string' ? value.replace('%', '').trim() : value); return Number.isFinite(number) ? number : null; }
function asObject(value: any): Record<string, any> { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; }
function rawData(snapshot: any) { return asObject(snapshot?.rawData); }
function baseStatusKind(status?: string | null) { const raw = String(status || '').toUpperCase(); if (FINISHED_STATUSES.includes(raw)) return 'finished'; if (HALF_TIME_STATUSES.includes(raw)) return 'halftime'; if (LIVE_STATUSES.includes(raw)) return 'live'; return 'scheduled'; }
function estimatedElapsed(matchDate: any) { const start = new Date(matchDate).getTime(); if (!Number.isFinite(start)) return null; return Math.floor((Date.now() - start) / 60000); }
function softPhase(match: any, latestSnapshot?: any) { const base = baseStatusKind(match.status); if (base !== 'scheduled') return base; if (toNullableNumber(latestSnapshot?.minute) && Number(latestSnapshot.minute) > 0) return 'live'; const elapsed = estimatedElapsed(match.matchDate); if (elapsed !== null && elapsed >= -KICKOFF_GRACE_MINUTES && elapsed <= SOFT_LIVE_MAX_MINUTES) return 'live'; return 'scheduled'; }
function inferredMinute(match: any, latestSnapshot: any, phase: string) { const snapshotMinute = toNullableNumber(latestSnapshot?.minute); if (snapshotMinute !== null && snapshotMinute > 0) return snapshotMinute; if (phase !== 'live') return null; const elapsed = estimatedElapsed(match.matchDate); if (elapsed === null) return 1; return Math.max(1, Math.min(130, elapsed)); }
function isTheStatsSnapshot(snapshot: any) { const p = String(snapshot?.provider || '').toUpperCase(); const raw = rawData(snapshot); return p.includes('THE_STATS') || String(raw.provider || '').toUpperCase().includes('THE_STATS'); }
function isISportsSnapshot(snapshot: any) { const p = String(snapshot?.provider || '').toUpperCase(); return p.includes('ISPORT') || p.includes('AUTOMATED_LIVE_INGEST') || p.includes('WORKER_ISPORTS'); }
function latestTheStatsSnapshot(snapshots: any[]) { return snapshots.find((snapshot) => isTheStatsSnapshot(snapshot) && rawData(snapshot)?.normalized) || snapshots.find(isTheStatsSnapshot) || null; }
function latestISportsSnapshot(snapshots: any[]) { return snapshots.find(isISportsSnapshot) || null; }
function statPairFromSnapshot(snapshot: any, key: string) { if (!snapshot) return null; const pair = asObject(rawData(snapshot)?.normalized?.liveStats?.stats?.[key]); let home = toNullableNumber(pair.home); let away = toNullableNumber(pair.away); const columns = COLUMN_KEYS[key]; if (columns) { home ??= toNullableNumber(snapshot[columns[0]]); away ??= toNullableNumber(snapshot[columns[1]]); } if (home === null && away === null) return null; return { home, away }; }
function buildMetrics(snapshots: any[], finished: boolean): MetricView[] { const theStats = latestTheStatsSnapshot(snapshots); const iSports = latestISportsSnapshot(snapshots); return METRIC_DEFS.map(([key, label, suffix]) => { const primary = key === 'attacks' || key === 'dangerousAttacks' ? null : statPairFromSnapshot(theStats, key); const fallback = statPairFromSnapshot(iSports, key); const pair = primary || fallback; return { key, label, home: pair?.home ?? null, away: pair?.away ?? null, suffix, available: Boolean(pair) }; }).filter((metric) => metric.available); }
function eventIcon(type: string) { const key = String(type || '').toLowerCase(); if (key.includes('goal')) return '⚽'; if (key.includes('yellow')) return '🟨'; if (key.includes('red')) return '🟥'; if (key.includes('sub')) return '🔁'; if (key.includes('shot')) return '🎯'; if (key.includes('corner')) return '🚩'; if (key.includes('penalty')) return '🥅'; if (key.includes('var')) return '📺'; if (key.includes('foul')) return '✋'; return '●'; }
function eventColor(type: string) { const key = String(type || '').toLowerCase(); if (key.includes('goal')) return '#F8C846'; if (key.includes('yellow')) return '#F8C846'; if (key.includes('red')) return '#FF5C5C'; if (key.includes('sub')) return '#38BDF8'; if (key.includes('shot')) return '#18E58F'; if (key.includes('corner')) return '#A78BFA'; return '#E5E7EB'; }
function sideFromTeam(teamId: string | null | undefined, homeTeamId: string, awayTeamId: string): AnimationTeamSide { if (teamId === homeTeamId) return 'home'; if (teamId === awayTeamId) return 'away'; return 'unknown'; }
function teamIdFromName(teamName: any, home: any, away: any) { const name = String(teamName || '').toLowerCase(); if (!name) return null; if (name.includes(String(home?.name || '').toLowerCase()) || String(home?.name || '').toLowerCase().includes(name)) return home.id; if (name.includes(String(away?.name || '').toLowerCase()) || String(away?.name || '').toLowerCase().includes(name)) return away.id; return null; }
function normalizeLiveRow(row: any, index: number, homeTeamId: string, awayTeamId: string) { const eventType = String(row?.eventType || row?.type || 'note'); const teamSide = sideFromTeam(row?.teamId, homeTeamId, awayTeamId); const spatial = inferLiveAnimationSpatial({ id: String(row?.id || `event-${index}`), type: eventType, detail: row?.detail || row?.eventLabel, minute: row?.minute, teamSide, index, explicitX: row?.x, explicitY: row?.y, explicitEndX: row?.endX, explicitEndY: row?.endY }); const x = row?.x === null || row?.x === undefined ? spatial.x : safeNumber(row.x, spatial.x); const y = row?.y === null || row?.y === undefined ? spatial.y : safeNumber(row.y, spatial.y); return { id: String(row?.id || `event-${index}`), sequenceNumber: safeNumber(row?.sequenceNumber, index + 1), minute: row?.minute === null || row?.minute === undefined ? null : safeNumber(row.minute, 0), second: row?.second === null || row?.second === undefined ? null : safeNumber(row.second, 0), teamId: row?.teamId || null, playerId: row?.playerId || null, playerName: row?.playerName || null, jerseyNumber: row?.jerseyNumber || null, eventType, eventLabel: row?.eventLabel || animationEventLabel(eventType), detail: row?.detail || row?.eventLabel || animationEventLabel(eventType), x: Math.max(0, Math.min(100, x)), y: Math.max(0, Math.min(100, y)), endX: row?.endX === null || row?.endX === undefined ? spatial.endX : Math.max(0, Math.min(100, safeNumber(row.endX, x))), endY: row?.endY === null || row?.endY === undefined ? spatial.endY : Math.max(0, Math.min(100, safeNumber(row.endY, y))), zone: row?.zone || spatial.zone, coordinateSource: row?.coordinateSource || spatial.coordinateSource, coordinateConfidence: row?.coordinateConfidence || spatial.coordinateConfidence, eventSide: row?.eventSide || spatial.eventSide, isInferred: row?.isInferred === null || row?.isInferred === undefined ? spatial.isInferred : Boolean(row.isInferred), anchorZone: row?.anchorZone || spatial.anchorZone, displayPriority: safeNumber(row?.displayPriority, spatial.displayPriority), provider: row?.provider || 'MATCH_EVENT_FALLBACK', icon: eventIcon(eventType), color: eventColor(eventType), createdAt: row?.createdAt ? new Date(row.createdAt).toISOString() : new Date().toISOString() }; }
function eventDedupeKey(event: any) { return [event.minute ?? '', String(event.eventType || '').toLowerCase(), event.teamId || '', String(event.playerName || '').toLowerCase(), String(event.detail || '').toLowerCase().slice(0, 90)].join('|'); }
function dedupeEvents(events: any[]) { const seen = new Set<string>(); return events.filter((event) => { const key = eventDedupeKey(event); if (seen.has(key)) return false; seen.add(key); return true; }); }
function theStatsEventsFromSnapshot(snapshot: any, match: any) { const list = rawData(snapshot)?.normalized?.eventsDetailed?.all; if (!Array.isArray(list)) return []; return dedupeEvents(list.map((row: any, index: number) => { const minute = toNullableNumber(row.minute); const eventType = normalizeAnimationEventType(row.type, row.detail); const teamId = row.teamId || teamIdFromName(row.teamName, match.homeTeam, match.awayTeam); return normalizeLiveRow({ id: `thestats-${row.sequence ?? index}-${minute ?? 'na'}-${row.type || 'event'}`, sequenceNumber: Math.max(0, Number(minute || 0)) * 100 + index + 1, minute, second: row.second ?? null, teamId, playerId: row.playerId || null, playerName: row.playerName || null, eventType, eventLabel: animationEventLabel(eventType), detail: row.detail || row.type || 'حدث', provider: 'FINAL_EVENTS', coordinateSource: 'INFERRED_ZONE', coordinateConfidence: 'MEDIUM', createdAt: snapshot.capturedAt || new Date() }, index, match.homeTeam.id, match.awayTeam.id); })); }
async function readAnimationEvents(match: any, afterSeq: number, limit: number, phase: string) { const finalSnapshot = latestTheStatsSnapshot(match.statsSnapshots || []); if (phase === 'finished' && finalSnapshot) return theStatsEventsFromSnapshot(finalSnapshot, match).filter((event) => Number(event.sequenceNumber || 0) > afterSeq).slice(0, limit); try { const rows = await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "LiveAnimationEvent" WHERE "matchId" = $1 AND "sequenceNumber" > $2 ORDER BY "sequenceNumber" ASC LIMIT $3`, match.id, afterSeq, limit); const liveRows = rows.filter((row) => !/THE_STATS|FOOTBALL_DATA|FOOTBALL-DATA/i.test(String(row.provider || ''))); if (liveRows.length) return dedupeEvents(liveRows.map((row, index) => normalizeLiveRow(row, index, match.homeTeam.id, match.awayTeam.id))); } catch {} const matchEvents = await prisma.matchEvent.findMany({ where: { matchId: match.id, OR: [{ sourceName: { contains: 'ISPORTS' } }, { sourceName: { contains: 'iSports' } }, { sourceName: { contains: 'Live Monitor' } }, { sourceName: { contains: 'Live Ingest' } }] }, orderBy: [{ minute: 'asc' }, { createdAt: 'asc' }], take: limit }).catch(() => [] as any[]); return dedupeEvents(matchEvents.map((event, index) => { const eventType = normalizeAnimationEventType(event.type, event.detail); return normalizeLiveRow({ id: event.id, sequenceNumber: safeNumber(event.minute, index + 1) * 100 + index + 1, minute: event.minute, teamId: event.teamId, playerId: event.playerId, playerName: event.playerName, eventType, eventLabel: animationEventLabel(eventType), detail: event.detail, provider: event.sourceName || 'LIVE_EVENT', createdAt: event.createdAt }, index, match.homeTeam.id, match.awayTeam.id); })).filter((event) => event.sequenceNumber > afterSeq); }
function buildClock(match: any, latestSnapshot: any, phase: string) { const minute = inferredMinute(match, latestSnapshot, phase); const confirmedMinute = toNullableNumber(latestSnapshot?.minute); const confirmedStart = baseStatusKind(match.status) === 'live' || baseStatusKind(match.status) === 'halftime' || Boolean(confirmedMinute && confirmedMinute > 0); if (phase === 'finished') return { label: 'انتهت المباراة', phaseLabel: 'نهاية المباراة', minute: null, verifiedStarted: true, verifiedFinished: true }; if (phase === 'halftime') return { label: 'استراحة بين الشوطين', phaseLabel: 'نهاية الشوط الأول', minute: 45, verifiedStarted: true, verifiedFinished: false }; if (phase === 'live') { const m = minute || 1; if (m <= 45) return { label: `الشوط الأول · د${m}`, phaseLabel: 'الشوط الأول', minute: m, verifiedStarted: confirmedStart, verifiedFinished: false }; if (m <= 60 && !confirmedMinute) return { label: `استراحة محتملة · د${m}`, phaseLabel: 'بين الشوطين تقديريًا', minute: m, verifiedStarted: false, verifiedFinished: false }; if (m <= 90) return { label: `الشوط الثاني · د${m}`, phaseLabel: 'الشوط الثاني', minute: m, verifiedStarted: confirmedStart, verifiedFinished: false }; return { label: `وقت بدل ضائع · د${m}`, phaseLabel: 'وقت بدل ضائع', minute: m, verifiedStarted: confirmedStart, verifiedFinished: false }; } return { label: 'لم تبدأ بعد', phaseLabel: 'قبل المباراة', minute: null, verifiedStarted: false, verifiedFinished: false }; }

export async function GET(req: Request, context: RouteContext) {
  const { id } = await context.params;
  const url = new URL(req.url);
  const afterSeq = Math.max(0, Math.floor(Number(url.searchParams.get('afterSeq') || 0)) || 0);
  const limit = Math.max(1, Math.min(80, Math.floor(Number(url.searchParams.get('limit') || 40)) || 40));
  const match = await prisma.match.findUnique({ where: { id }, include: { homeTeam: { select: { id: true, name: true, code: true, image: true } }, awayTeam: { select: { id: true, name: true, code: true, image: true } }, statsSnapshots: { orderBy: { capturedAt: 'desc' }, take: 12 } } });
  if (!match) return NextResponse.json({ ok: false, error: 'Match not found' }, { status: 404, headers: { 'Cache-Control': 'no-store' } });
  const snapshots = match.statsSnapshots || [];
  const finalSnapshot = latestTheStatsSnapshot(snapshots);
  const preliminaryLatest = snapshots[0] || null;
  const phase = softPhase(match, preliminaryLatest);
  const latestSnapshot = phase === 'finished' && finalSnapshot ? finalSnapshot : preliminaryLatest;
  const events = await readAnimationEvents(match, afterSeq, limit, phase);
  const lastSequence = events.reduce((max, event) => Math.max(max, Number(event.sequenceNumber || 0)), afterSeq);
  const homeTheme = getTeamVisualTheme(match.homeTeam.code, match.homeTeam.name);
  const awayTheme = getTeamVisualTheme(match.awayTeam.code, match.awayTeam.name);
  const clock = buildClock(match, latestSnapshot, phase);
  return NextResponse.json({ ok: true, mode: 'db_only_live_animation_state_v3_soft_live', matchId: match.id, title: `${match.homeTeam.name} ضد ${match.awayTeam.name}`, phase, status: match.status, minute: clock.minute ?? latestSnapshot?.minute ?? null, clock, score: { home: safeNumber(latestSnapshot?.homeScore ?? match.homeScore, 0), away: safeNumber(latestSnapshot?.awayScore ?? match.awayScore, 0) }, teams: { home: { ...match.homeTeam, theme: homeTheme }, away: { ...match.awayTeam, theme: awayTheme } }, visualTheme: { home: homeTheme, away: awayTheme }, stats: buildMetrics(snapshots, phase === 'finished'), lastSequence, events, source: phase === 'finished' && finalSnapshot ? 'final_timeline' : 'live_or_soft_live_events', lastUpdatedAt: latestSnapshot?.capturedAt ? latestSnapshot.capturedAt.toISOString() : new Date().toISOString() }, { headers: { 'Cache-Control': 'no-store' } });
}
