'use client';

import type { ReactNode } from 'react';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, Newspaper, Pencil, Save, Trash2, Video, X } from 'lucide-react';

type DailyDigest = { id: string; digestDate: string; headline: string; summary: string; videoScript: string; facebookPost?: string | null; youtubeTitle?: string | null; youtubeDescription?: string | null; infographicPoints?: any; status?: string };
type MatchDigest = { id: string; matchId: string; matchTitle: string; scoreLine: string; statusLabel: string; summary: string; turningPoint?: string | null; videoScript: string; facebookPost?: string | null; infographicPoints?: any; status?: string };
type PressNews = { id: string; title: string; body: string; category?: string; sourceName?: string };
type Props = { dailyDigests: DailyDigest[]; matchDigests: MatchDigest[]; pressNews: PressNews[] };
type EditState = { kind: 'daily' | 'match'; key: string; title: string; summary: string; script: string } | null;

export default function ContentStudioManager({ dailyDigests, matchDigests, pressNews }: Props) {
  const [daily, setDaily] = useState(dailyDigests);
  const [matches, setMatches] = useState(matchDigests);
  const [news, setNews] = useState(pressNews);
  const [edit, setEdit] = useState<EditState>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  function startDaily(item: DailyDigest) { setEdit({ kind: 'daily', key: item.digestDate, title: item.headline, summary: item.summary, script: item.videoScript }); }
  function startMatch(item: MatchDigest) { setEdit({ kind: 'match', key: item.matchId, title: item.matchTitle, summary: item.summary, script: item.videoScript }); }
  async function saveEdit() { if (!edit) return; setSaving(true); setError(null); setMessage(null); try { const isDaily = edit.kind === 'daily'; const original: any = isDaily ? daily.find((item) => item.digestDate === edit.key) : matches.find((item) => item.matchId === edit.key); const endpoint = isDaily ? '/api/admin/daily-digests' : '/api/admin/match-digests'; const body = isDaily ? { ...original, digestDate: edit.key, headline: edit.title, summary: edit.summary, videoScript: edit.script } : { ...original, matchId: edit.key, matchTitle: edit.title, summary: edit.summary, videoScript: edit.script, scoreLine: original?.scoreLine || 'VS', statusLabel: original?.statusLabel || 'منشور' }; const res = await fetch(endpoint, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'فشل الحفظ'); if (isDaily) setDaily((items) => items.map((item) => item.digestDate === edit.key ? { ...item, headline: edit.title, summary: edit.summary, videoScript: edit.script } : item)); else setMatches((items) => items.map((item) => item.matchId === edit.key ? { ...item, matchTitle: edit.title, summary: edit.summary, videoScript: edit.script } : item)); setEdit(null); setMessage('تم حفظ التعديل.'); } catch (err: any) { setError(err?.message || 'فشل الحفظ'); } finally { setSaving(false); } }
  async function deleteDaily(digestDate: string) { if (!confirm('حذف ملخص اليوم المحفوظ؟')) return; setError(null); setMessage(null); const res = await fetch(`/api/admin/daily-digests?digestDate=${encodeURIComponent(digestDate)}`, { method: 'DELETE' }); if (res.ok) { setDaily((items) => items.filter((item) => item.digestDate !== digestDate)); setMessage('تم حذف ملخص اليوم.'); } else setError('فشل حذف ملخص اليوم.'); }
  async function deleteMatch(matchId: string) { if (!confirm('حذف ملخص المباراة المحفوظ؟')) return; setError(null); setMessage(null); const res = await fetch(`/api/admin/match-digests?matchId=${encodeURIComponent(matchId)}`, { method: 'DELETE' }); if (res.ok) { setMatches((items) => items.filter((item) => item.matchId !== matchId)); setMessage('تم حذف ملخص المباراة.'); } else setError('فشل حذف ملخص المباراة.'); }
  async function deleteNews(id: string) { if (!confirm('حذف الخبر؟')) return; setError(null); setMessage(null); const res = await fetch(`/api/admin/press-news?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); if (res.ok) { setNews((items) => items.filter((item) => item.id !== id)); setMessage('تم حذف الخبر.'); } else setError('فشل حذف الخبر.'); }
  return <div className="space-y-6">{message && <div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm font-bold text-emerald-200">{message}</div>}{error && <div className="rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm font-bold text-red-200">{error}</div>}{edit && <section className="rounded-[2rem] border border-[#FFD700]/20 bg-[#FFD700]/[0.04] p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-xl font-black">تعديل المحتوى</h2><button type="button" onClick={() => setEdit(null)} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black text-gray-300"><X size={14} /></button></div><div className="grid gap-4"><input value={edit.title} onChange={(event) => setEdit({ ...edit, title: event.target.value })} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm font-bold text-white outline-none" /><textarea value={edit.summary} onChange={(event) => setEdit({ ...edit, summary: event.target.value })} rows={4} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm font-bold leading-7 text-white outline-none" /><textarea value={edit.script} onChange={(event) => setEdit({ ...edit, script: event.target.value })} rows={6} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm font-bold leading-7 text-white outline-none" /><button disabled={saving} onClick={saveEdit} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#FFD700] px-5 py-3 text-sm font-black text-black disabled:opacity-60"><Save size={16} /> حفظ التعديل</button></div></section>}<section className="grid gap-6 lg:grid-cols-3"><Column title="ملخصات اليوم" icon={<CalendarDays className="text-[#FFD700]" />} empty="لا توجد ملخصات يومية محفوظة.">{daily.map((item) => <Card key={item.id} title={item.headline} body={item.summary} meta={item.digestDate} href={`/daily-summary/${item.digestDate}`} onEdit={() => startDaily(item)} onDelete={() => deleteDaily(item.digestDate)} />)}</Column><Column title="ملخصات المباريات" icon={<Video className="text-[#0FF0FC]" />} empty="لا توجد ملخصات مباريات محفوظة.">{matches.map((item) => <Card key={item.id} title={item.matchTitle} body={item.summary} meta={item.scoreLine} href={`/match-digests/${item.matchId}`} onEdit={() => startMatch(item)} onDelete={() => deleteMatch(item.matchId)} />)}</Column><Column title="الأخبار" icon={<Newspaper className="text-emerald-300" />} empty="لا توجد أخبار محفوظة.">{news.map((item) => <Card key={item.id} title={item.title} body={item.body} meta={item.category || item.sourceName || 'خبر'} href="/news" editHref="/admin/news" onDelete={() => deleteNews(item.id)} />)}</Column></section></div>;
}
function Column({ title, icon, empty, children }: { title: string; icon: ReactNode; empty: string; children: ReactNode }) { const hasItems = Array.isArray(children) ? children.length > 0 : Boolean(children); return <section className="rounded-[2rem] border border-white/10 bg-white/[0.035] p-5"><h2 className="mb-4 flex items-center gap-2 text-xl font-black">{icon}{title}</h2>{hasItems ? <div className="space-y-3">{children}</div> : <div className="rounded-2xl border border-dashed border-white/10 bg-black/20 p-6 text-center text-sm font-bold text-gray-500">{empty}</div>}</section>; }
function Card({ title, body, meta, href, editHref, onEdit, onDelete }: { title: string; body: string; meta: string; href: string; editHref?: string; onEdit?: () => void; onDelete: () => void }) { return <article className="rounded-2xl border border-white/8 bg-black/25 p-4"><Link href={href} className="block"><div className="mb-2 text-[11px] font-black text-gray-500">{meta}</div><h3 className="line-clamp-2 font-black leading-6 text-white">{title}</h3><p className="mt-2 line-clamp-3 text-xs font-bold leading-6 text-gray-500">{body}</p></Link><div className="mt-3 flex flex-wrap gap-2">{onEdit ? <button type="button" onClick={onEdit} className="inline-flex items-center gap-1 rounded-xl border border-[#0FF0FC]/20 bg-[#0FF0FC]/10 px-3 py-2 text-[11px] font-black text-[#0FF0FC]"><Pencil size={13} /> تعديل</button> : editHref ? <Link href={editHref} className="inline-flex items-center gap-1 rounded-xl border border-[#0FF0FC]/20 bg-[#0FF0FC]/10 px-3 py-2 text-[11px] font-black text-[#0FF0FC]"><Pencil size={13} /> تعديل</Link> : null}<button type="button" onClick={onDelete} className="inline-flex items-center gap-1 rounded-xl border border-red-400/20 bg-red-400/10 px-3 py-2 text-[11px] font-black text-red-300"><Trash2 size={13} /> حذف</button><Link href={href} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-[11px] font-black text-gray-400">فتح <ArrowLeft size={12} /></Link></div></article>; }
