'use client';
import {useMemo,useState} from 'react';
import MatchAutoRefresh from '@/components/match-center/MatchAutoRefresh';
import type {MatchPageData,MatchEventView,MatchPlayerStatItem} from '@/lib/match-page/types';
import InteractiveEventPitch from './InteractiveEventPitch';
import PanelSmall from './PanelSmall';
import TeamInlineFlag from './TeamInlineFlag';

type Tab='overview'|'events'|'lineups'|'analysis'|'group'|'articles';
const tabs:Tab[]=['overview','events','lineups','analysis','group','articles'];
const names:any={overview:'نظرة عامة',events:'الأحداث',lineups:'التشكيلات وأداء اللاعبين',analysis:'التحليل',group:'المجموعة',articles:'المقالات'};
const ar=new Intl.NumberFormat('ar-EG');
const f=(v:any,s='')=>v===null||v===undefined||v===''?'—':Number.isFinite(Number(v))?`${ar.format(Number(v))}${s}`:String(v);
const dt=(v:string)=>new Intl.DateTimeFormat('ar-EG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const txt=(v:any)=>String(v||'').toLowerCase();
function eventLabel(e:MatchEventView){const x=txt(`${e.type} ${e.detail}`);if(x.includes('goal')||x.includes('هدف'))return'هدف';if(x.includes('red')||x.includes('حمراء'))return'بطاقة حمراء';if(x.includes('yellow')||x.includes('صفراء'))return'بطاقة صفراء';if(x.includes('sub')||x.includes('تبديل'))return'تبديل';if(x.includes('pen'))return'ركلة جزاء';if(x.includes('var'))return'VAR';if(x.includes('foul'))return'مخالفة';return'حدث'}
function side(e:MatchEventView,d:MatchPageData){return e.teamId===d.homeTeam.id||e.teamId===d.homeTeam.code?'home':e.teamId===d.awayTeam.id||e.teamId===d.awayTeam.code?'away':'neutral'}
function Box(p:{title?:string;children:any}){return <section className="rounded-[1.4rem] border border-white/10 bg-white/[0.045] p-4">{p.title&&<h2 className="mb-4 text-xl font-black text-white">{p.title}</h2>}{p.children}</section>}
function Avatar({p,e}:{p?:MatchPlayerStatItem;e?:MatchEventView}){const name=p?.playerName||e?.playerName||'؟';const img=p?.image||e?.playerImage;const num=p?.number||e?.playerNumber;return <span className="relative inline-flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-black/40">{img?<img src={img} className="h-full w-full object-cover"/>:<b className="text-xs text-[#F8C846]">{String(name).slice(0,2)}</b>}{num&&<i className="absolute bottom-0 left-0 rounded-full bg-[#F8C846] px-1 text-[9px] not-italic text-black">{num}</i>}</span>}
function Header({d}:{d:MatchPageData}){return <Box><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><TeamInlineFlag team={d.homeTeam} className="font-black text-white"/><div className="rounded-2xl bg-black/35 px-4 py-2 text-center"><b className="text-4xl sm:text-6xl"><span className="text-[#F8C846]">{f(d.score.home)}</span> - {f(d.score.away)}</b><p className="text-xs text-slate-400">{d.groupLabel||d.stageLabel}</p></div><TeamInlineFlag team={d.awayTeam} className="justify-end text-left font-black text-white"/></div><div className="mt-3 grid gap-2 rounded-2xl bg-black/20 p-3 text-xs text-slate-300 sm:grid-cols-3"><span>{dt(d.matchDate)}</span><span>{d.venue||'غير متوفر'}</span><span>{d.referee||'غير متوفر'}</span></div></Box>}
function Overview({d}:{d:MatchPageData}){const rows=d.stats.filter(m=>m.available);return <Box title="نظرة عامة"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map(m=><article key={m.key} className="rounded-2xl bg-black/25 p-3"><div className="flex justify-between gap-2"><b className="text-[#F8C846]">{f(m.home,m.suffix)}</b><span className="text-xs font-black">{m.label}</span><b className="text-[#18E58F]">{f(m.away,m.suffix)}</b></div></article>)}</div></Box>}
function Events({d,events}:{d:MatchPageData;events:MatchEventView[]}){return <Box title="الأحداث والملعب التفاعلي"><div className="grid gap-4 xl:grid-cols-[420px_1fr]"><InteractiveEventPitch events={events}/><div className="space-y-3">{events.map(e=>{const s=side(e,d),team=s==='home'?d.homeTeam:s==='away'?d.awayTeam:null;return <article key={e.id} className="rounded-2xl border border-white/10 bg-black/25 p-3"><div className="flex items-center gap-3"><Avatar e={e}/><div><b>{e.minuteLabel} · {eventLabel(e)}{e.playerName?` — ${e.playerName}`:''}</b><p className="text-xs text-slate-400">{team?<TeamInlineFlag team={team}/>:null}</p></div></div></article>})}</div></div></Box>}
function byTeam(d:MatchPageData,home:boolean){const t=home?d.homeTeam:d.awayTeam;const all=d.advanced.playerStats||[];let r=all.filter(p=>p.teamId===t.id||p.teamId===t.code||txt(p.teamName).includes(txt(t.name)));if(!r.length&&all.length){const half=Math.ceil(all.length/2);r=home?all.slice(0,half):all.slice(half)}return r}
function Player({p}:{p:MatchPlayerStatItem}){return <article className="mb-2 rounded-2xl bg-black/25 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Avatar p={p}/><b>{p.playerName}</b></div><b className="text-[#18E58F]">{f(p.rating)}</b></div><div className="mt-2 grid grid-cols-4 text-center text-xs text-slate-400"><span>د <b className="block text-white">{f(p.minutes)}</b></span><span>هدف <b className="block text-white">{f(p.goals)}</b></span><span>أسيست <b className="block text-white">{f(p.assists)}</b></span><span>تسديد <b className="block text-white">{f(p.shotsOnTarget??p.shots)}</b></span></div></article>}
function Lineups({d}:{d:MatchPageData}){const block=(home:boolean)=>{const team=home?d.homeTeam:d.awayTeam;const rows=byTeam(d,home);const starters=rows.filter(p=>p.started).length?rows.filter(p=>p.started):rows.slice(0,11);const subs=rows.slice(11);return <section className="rounded-2xl bg-black/20 p-3"><h3 className="mb-3 font-black"><TeamInlineFlag team={team}/></h3><p className="mb-2 text-xs text-[#F8C846]">الأساسيون</p>{starters.map((p,i)=><Player key={`${p.playerName}-s-${i}`} p={p}/>) }<p className="mb-2 mt-4 text-xs text-[#18E58F]">البدلاء/المستبدلون</p>{subs.map((p,i)=><Player key={`${p.playerName}-b-${i}`} p={p}/>)}</section>};return <Box title="التشكيلات وأداء اللاعبين"><div className="grid gap-4 lg:grid-cols-2">{block(true)}{block(false)}</div></Box>}
function Group({d}:{d:MatchPageData}){return <Box title="موقف المجموعة حتى تاريخ المباراة"><table className="w-full text-xs"><tbody>{d.groupStandings.map(r=><tr key={r.teamId} className="border-t border-white/10"><td className="p-2">{r.rank}</td><td className="p-2"><TeamInlineFlag team={{code:r.code,name:r.teamName,image:r.image}}/></td><td className="p-2">{r.played}</td><td className="p-2 text-[#F8C846]">{r.points}</td></tr>)}</tbody></table></Box>}
function Articles({d}:{d:MatchPageData}){return <Box title="المقالات">{d.relatedArticles.map(a=><a key={a.id} href={a.href} className="block rounded-2xl border border-white/10 p-3">{a.title}</a>)}</Box>}
export default function FinalRichPage({data}:{data:MatchPageData}){const[tab,setTab]=useState<Tab>(data.status.isLive?'events':'overview');const events=useMemo(()=>data.events||[],[data.events]);return <main className="min-h-screen bg-[#07110D] px-3 py-3 text-white" dir="rtl"><MatchAutoRefresh intervalMs={data.status.isLive?25000:90000}/><div className="mx-auto max-w-7xl space-y-4"><Header d={data}/><nav className="sticky top-0 z-30 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#07110D]/95 p-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`h-10 shrink-0 rounded-xl px-3 text-xs font-black ${tab===t?'bg-[#18E58F] text-black':'bg-white/[0.05]'}`}>{names[t]}</button>)}</nav>{tab==='overview'&&<Overview d={data}/>} {tab==='events'&&<Events d={data} events={events}/>} {tab==='lineups'&&<Lineups d={data}/>} {tab==='analysis'&&<PanelSmall data={data}/>} {tab==='group'&&<Group d={data}/>} {tab==='articles'&&<Articles d={data}/>}</div></main>}
