'use client';

import { useMemo, useState } from 'react';
import MatchAutoRefresh from '@/components/match-center/MatchAutoRefresh';
import { getArabicTeamName } from '@/lib/teamDisplay';
import { getTeamFlagUrl } from '@/lib/teamFlags';
import type { MatchEventView, MatchPageData, MatchPlayerStatItem } from '@/lib/match-page/types';

type Tab = 'overview' | 'events' | 'lineups' | 'analysis' | 'group' | 'articles';
const ar = new Intl.NumberFormat('ar-EG');
const tabs: { id: Tab; label: string }[] = [
  { id: 'overview', label: 'نظرة عامة' },
  { id: 'events', label: 'الأحداث' },
  { id: 'lineups', label: 'التشكيلات وأداء اللاعبين' },
  { id: 'analysis', label: 'التحليل' },
  { id: 'group', label: 'المجموعة' },
  { id: 'articles', label: 'المقالات' },
];
function f(v: any, s = '') { if (v === null || v === undefined || v === '') return '—'; const n = Number(v); return Number.isFinite(n) ? `${Number.isInteger(n) ? ar.format(n) : n.toLocaleString('ar-EG', { maximumFractionDigits: 2 })}${s}` : String(v); }
function tn(t: { code?: string | null; name?: string | null }) { return getArabicTeamName(t.code, t.name); }
function dt(v: string) { return new Intl.DateTimeFormat('ar-EG', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(v)); }
function flag(t: MatchPageData['homeTeam'], width = 120) { return getTeamFlagUrl({ code: t.code, name: tn(t), image: t.image }, width) || t.image || null; }
function clean(v?: string | number | null) { return String(v || '').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f\u064B-\u065F\u0670]/g, '').replace(/[^a-z0-9\u0600-\u06ff]+/g, ' ').replace(/\s+/g, ' ').trim(); }
function k(e: MatchEventView) { const x = `${e.type} ${e.detail}`.toLowerCase(); if (x.includes('goal') || x.includes('هدف')) return ['هدف', '⚽']; if (x.includes('red') || x.includes('حمراء')) return ['بطاقة حمراء', '🟥']; if (x.includes('yellow') || x.includes('صفراء')) return ['بطاقة صفراء', '🟨']; if (x.includes('sub') || x.includes('تبديل')) return ['تبديل', '🔁']; if (x.includes('pen')) return ['ركلة جزاء', '🎯']; if (x.includes('var')) return ['مراجعة VAR', '📺']; if (x.includes('foul')) return ['مخالفة', '🧱']; if (x.includes('added')) return ['وقت بدل ضائع', '⏱️']; if (x.includes('period')) return ['نهاية الشوط', '⌛']; return ['حدث', e.icon || '●']; }
function side(e: MatchEventView, d: MatchPageData) { if (e.teamId === d.homeTeam.id || e.teamId === d.homeTeam.code) return 'home'; if (e.teamId === d.awayTeam.id || e.teamId === d.awayTeam.code) return 'away'; return 'neutral'; }
function historyOf(d: MatchPageData) { return d.history || { homeRecentForm: [], awayRecentForm: [], headToHead: [], homeWorldCupHistory: `تاريخ مشاركات ${tn(d.homeTeam)} في كأس العالم غير متوفر في قاعدة البيانات الحالية.`, awayWorldCupHistory: `تاريخ مشاركات ${tn(d.awayTeam)} في كأس العالم غير متوفر في قاعدة البيانات الحالية.` }; }
function Box(p: { title?: string; children: any; hint?: string }) { return <section className="rounded-[1.4rem] border border-white/10 bg-white/[0.045] p-4 shadow-[0_18px_48px_rgba(0,0,0,.18)]">{p.title && <div className="mb-4"><h2 className="text-xl font-black text-white">{p.title}</h2>{p.hint && <p className="mt-1 text-xs text-slate-400">{p.hint}</p>}</div>}{p.children}</section>; }
function TeamFlag({ team, small = false }: { team: MatchPageData['homeTeam']; small?: boolean }) { const src = flag(team, small ? 64 : 140); return <span className={`inline-flex shrink-0 items-center justify-center overflow-hidden border border-white/10 bg-black/35 ${small ? 'h-7 w-9 rounded-lg' : 'h-14 w-16 rounded-2xl sm:h-20 sm:w-24'}`}>{src ? <img src={src} alt={tn(team)} className="h-full w-full object-cover" /> : <b className="text-xs text-[#F8C846]">{team.code || '—'}</b>}</span>; }
function Avatar({ name, image, number }: { name?: string | null; image?: string | null; number?: any }) { return <span className="relative inline-flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full border border-white/10 bg-black/40">{image ? <img src={image} alt={name || 'player'} className="h-full w-full object-cover" /> : <b className="text-xs text-[#F8C846]">{String(name || '؟').slice(0, 2)}</b>}{number && <i className="absolute bottom-0 left-0 rounded-full bg-[#F8C846] px-1 text-[9px] not-italic text-black">{number}</i>}</span>; }
function Header({ d }: { d: MatchPageData }) { return <header className="rounded-[1.6rem] border border-white/10 bg-white/[0.045] p-4 shadow-[0_24px_70px_rgba(0,0,0,.24)]"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><span className="rounded-full border border-[#18E58F]/30 bg-[#18E58F]/10 px-3 py-1.5 text-xs font-black text-[#18E58F]">{d.status.shortLabel || d.status.label}</span><span className="rounded-full border border-white/10 bg-black/25 px-3 py-1.5 text-xs font-bold text-slate-400">آخر تحديث: {dt(d.lastUpdatedAt)}</span></div><div className="grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2 sm:gap-5"><div className="flex min-w-0 items-center gap-3 text-right"><TeamFlag team={d.homeTeam} /><div className="min-w-0"><h1 className="truncate text-base font-black text-white sm:text-2xl">{tn(d.homeTeam)}</h1><p className="mt-1 text-[11px] font-bold text-slate-400">{d.homeTeam.code || '—'}</p></div></div><div className="rounded-2xl border border-white/10 bg-black/35 px-3 py-2 text-center sm:px-6 sm:py-3"><div className="flex items-center justify-center gap-2 tabular-nums sm:gap-4"><b className="text-4xl font-black text-[#F8C846] sm:text-6xl">{f(d.score.home)}</b><span className="text-2xl font-black text-white/60 sm:text-5xl">-</span><b className="text-4xl font-black text-white sm:text-6xl">{f(d.score.away)}</b></div><p className="mt-1 text-[11px] font-bold text-slate-400">{d.groupLabel || d.stageLabel}</p></div><div className="flex min-w-0 flex-row-reverse items-center gap-3 text-left"><TeamFlag team={d.awayTeam} /><div className="min-w-0"><h1 className="truncate text-base font-black text-white sm:text-2xl">{tn(d.awayTeam)}</h1><p className="mt-1 text-[11px] font-bold text-slate-400">{d.awayTeam.code || '—'}</p></div></div></div><div className="mt-3 grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-3 text-xs font-bold text-slate-300 sm:grid-cols-3"><span><b className="text-[#18E58F]">الموعد:</b> {dt(d.matchDate)}</span><span><b className="text-[#18E58F]">الملعب:</b> {d.venue || 'غير متوفر'}</span><span><b className="text-[#18E58F]">الحكم:</b> {d.referee || 'غير متوفر'}</span></div></header>; }
function Overview({ d }: { d: MatchPageData }) { const rows = d.stats.filter((m) => m.available); return <Box title="نظرة عامة" hint="الإحصائيات تظهر هنا مباشرة، لذلك تم إلغاء تاب الإحصائيات."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map((m) => <article key={m.key} className="rounded-2xl border border-white/10 bg-black/25 p-3"><div className="flex justify-between"><b className="text-[#F8C846]">{f(m.home, m.suffix)}</b><span className="text-xs font-black">{m.label}</span><b className="text-[#18E58F]">{f(m.away, m.suffix)}</b></div></article>)}</div></Box>; }
function Events({ d, e }: { d: MatchPageData; e: MatchEventView[] }) { return <Box title="خط أحداث المباراة" hint="كل جانب لمنتخب، والحدث بالعربي مع اللاعب وصورته ورقمه عند توفرهما، بدون ذكر المصدر."><div className="relative space-y-5 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="absolute inset-y-0 left-1/2 w-px bg-white/10" />{e.map((ev) => { const [label, icon] = k(ev), s = side(ev, d); const card = <div className="rounded-2xl border border-white/10 bg-black/35 p-3"><div className="flex items-center gap-3"><Avatar name={ev.playerName} image={ev.playerImage} number={ev.playerNumber} /><div><b>{label}{ev.playerName ? ` — ${ev.playerName}` : ''}</b><p className="text-xs text-slate-400">{s === 'home' ? tn(d.homeTeam) : s === 'away' ? tn(d.awayTeam) : 'المباراة'}</p></div></div></div>; return <article key={ev.id} className="relative grid items-center gap-3 md:grid-cols-[1fr_56px_1fr]"><div>{s !== 'away' && card}</div><div className="z-10 mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#070b18]">{icon}</div><div>{s !== 'home' && card}</div><span className="absolute left-1/2 top-0 -translate-x-1/2 rounded-full bg-[#07110D] px-2 text-xs text-[#F8C846]">{ev.minuteLabel}</span></article>; })}</div></Box>; }
function Player({ p }: { p: MatchPlayerStatItem }) { return <article className="mb-2 rounded-2xl border border-white/10 bg-black/25 p-3"><div className="flex items-center justify-between"><div className="flex min-w-0 items-center gap-3"><Avatar name={p.playerName} image={p.image} number={p.number} /><div className="min-w-0"><b className="block truncate text-sm text-white">{p.playerName}</b><p className="text-xs text-slate-500">{p.position || (p.started ? 'أساسي' : 'شارك')}</p></div></div><b className="text-[#18E58F]">{f(p.rating)}</b></div><div className="mt-2 grid grid-cols-4 text-center text-xs text-slate-400"><span>د <b className="block text-white">{f(p.minutes)}</b></span><span>هدف <b className="block text-white">{f(p.goals)}</b></span><span>أسيست <b className="block text-white">{f(p.assists)}</b></span><span>تسديد <b className="block text-white">{f(p.shotsOnTarget ?? p.shots)}</b></span></div></article>; }
function teamRows(d: MatchPageData, team: 'home' | 'away') { const t = team === 'home' ? d.homeTeam : d.awayTeam; const all = d.advanced.playerStats || []; let rows = all.filter((p) => p.teamId === t.id || p.teamId === t.code || clean(p.teamName).includes(clean(t.name)) || clean(p.teamName).includes(clean(t.code))); if (!rows.length && all.length) { const half = Math.ceil(all.length / 2); rows = team === 'home' ? all.slice(0, half) : all.slice(half); } return rows; }
function TeamPlayers({ d, team }: { d: MatchPageData; team: 'home' | 'away' }) { const t = team === 'home' ? d.homeTeam : d.awayTeam; const all = teamRows(d, team); let starters = all.filter((p) => p.started === true); let subs = all.filter((p) => p.started !== true && (Number(p.minutes || 0) > 0 || p.played || p.playerSubbedOn || p.playerSubbedOff)); if (!starters.length && all.length) { starters = all.slice(0, 11); subs = all.slice(11); } return <section className="rounded-2xl border border-white/10 bg-black/20 p-3"><h3 className="mb-3 flex items-center gap-2 font-black"><TeamFlag team={t} small /> {tn(t)}</h3><p className="mb-2 text-xs font-black text-[#F8C846]">الأساسيون</p>{starters.length ? starters.map((p, i) => <Player key={`${p.playerId || p.playerName}-s-${i}`} p={p} />) : <p className="text-xs text-slate-500">لا توجد قائمة أساسيين محفوظة.</p>}<p className="mb-2 mt-4 text-xs font-black text-[#18E58F]">البدلاء/المستبدلون</p>{subs.length ? subs.map((p, i) => <Player key={`${p.playerId || p.playerName}-b-${i}`} p={p} />) : <p className="text-xs text-slate-500">لا توجد بدلاء محفوظون.</p>}</section>; }
function Lineups({ d }: { d: MatchPageData }) { return <Box title="التشكيلات وأداء اللاعبين" hint="إذا لم يأتِ teamId واضحًا من المزود يتم تقسيم قائمة اللاعبين المتاحة بين المنتخبين كـ fallback."><div className="grid gap-4 lg:grid-cols-2"><TeamPlayers d={d} team="home" /><TeamPlayers d={d} team="away" /></div></Box>; }
function Analysis({ d }: { d: MatchPageData }) { const h = historyOf(d); return <Box title="التحليل"><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="font-black">آخر ٥ مباريات: {tn(d.homeTeam)}</h3>{h.homeRecentForm.length ? h.homeRecentForm.map((r) => <p key={r.id} className="text-xs text-slate-300">{r.opponentName} · {f(r.teamScore)}-{f(r.opponentScore)} · {dt(r.date)}</p>) : <p className="text-xs text-slate-500">لا توجد مباريات محفوظة كافية.</p>}<h3 className="mt-3 font-black">آخر ٥ مباريات: {tn(d.awayTeam)}</h3>{h.awayRecentForm.length ? h.awayRecentForm.map((r) => <p key={r.id} className="text-xs text-slate-300">{r.opponentName} · {f(r.teamScore)}-{f(r.opponentScore)} · {dt(r.date)}</p>) : <p className="text-xs text-slate-500">لا توجد مباريات محفوظة كافية.</p>}</div><div><h3 className="font-black text-[#F8C846]">المواجهات المباشرة</h3>{h.headToHead.length ? h.headToHead.map((x) => <p key={x.id} className="text-xs text-slate-300">{x.homeTeamName} {f(x.homeScore)}-{f(x.awayScore)} {x.awayTeamName}</p>) : <p className="text-xs text-slate-500">لا توجد مواجهات مباشرة محفوظة بين المنتخبين.</p>}<h3 className="mt-3 font-black text-[#18E58F]">تاريخ كأس العالم</h3><p className="text-sm text-slate-300">{h.homeWorldCupHistory}</p><p className="text-sm text-slate-300">{h.awayWorldCupHistory}</p></div></div></Box>; }
function Group({ d }: { d: MatchPageData }) { return <Box title="موقف المجموعة حتى تاريخ المباراة"><table className="w-full text-xs"><tbody>{d.groupStandings.map((r) => <tr key={r.teamId} className="border-t border-white/10"><td className="p-2">{r.rank}</td><td className="p-2">{r.teamName}</td><td className="p-2">{r.played}</td><td className="p-2 text-[#F8C846]">{r.points}</td></tr>)}</tbody></table></Box>; }
function Articles({ d }: { d: MatchPageData }) { return <Box title="المقالات">{d.relatedArticles.map((a) => <a key={a.id} href={a.href} className="block rounded-2xl border border-white/10 p-3">{a.title}</a>)}</Box>; }

export default function ProfessionalMatchTabsPageRich({ data }: { data: MatchPageData }) { const [tab, setTab] = useState<Tab>('overview'); const events = useMemo(() => data.events || [], [data.events]); return <main className="min-h-screen bg-[#07110D] px-3 py-3 text-white" dir="rtl"><MatchAutoRefresh intervalMs={data.status.isLive ? 25000 : 90000} /><div className="mx-auto max-w-7xl space-y-4"><Header d={data} /><nav className="sticky top-0 z-30 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#07110D]/95 p-2 backdrop-blur">{tabs.map((x) => <button key={x.id} onClick={() => setTab(x.id)} className={`h-10 shrink-0 rounded-xl px-3 text-xs font-black ${tab === x.id ? 'bg-[#18E58F] text-black' : 'bg-white/[0.05]'}`}>{x.label}</button>)}</nav>{tab === 'overview' && <Overview d={data} />}{tab === 'events' && <Events d={data} e={events} />}{tab === 'lineups' && <Lineups d={data} />}{tab === 'analysis' && <Analysis d={data} />}{tab === 'group' && <Group d={data} />}{tab === 'articles' && <Articles d={data} />}</div></main>; }
